# Isolation Forest test

In [76]:
import pandas as pd
import numpy as np
from pathlib import Path

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix, root_mean_squared_error
from sklearn.linear_model import LinearRegression

In [78]:
project_folder = Path.cwd().parent

dataset_path = project_folder / "data/test/creditcard.csv"

dataset_path

WindowsPath('c:/Users/hp/Documents/School/anomaly-detection/data/test/creditcard.csv')

In [79]:
creditcard_df = pd.read_csv(dataset_path)

creditcard_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [80]:
creditcard_df.shape

(284807, 31)

In [81]:
creditcard_df["Deltatime"] = creditcard_df["Time"].diff()

creditcard_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,Deltatime
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0,NaN
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,1.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0,1.0

In [82]:
creditcard_classless_df = creditcard_df.drop(columns=["Class"])

creditcard_classless_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Deltatime
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,NaN
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,1.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,1.0

In [83]:
y = creditcard_df["Class"]

X = creditcard_df.drop(columns=["Class"])

In [84]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=24,
    stratify=y
)

In [85]:
model = IsolationForest(random_state=0, n_jobs=-1, contamination=0.0017)

model.fit(X_train)

IsolationForest(contamination=0.0017, n_jobs=-1, random_state=0)

In [86]:
y_pred = model.predict(X_test)

y_pred = np.where(y_pred == -1, 1, 0)

y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(56962,))

In [87]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56787    77]
 [   70    28]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.27      0.29      0.28        98

    accuracy                           1.00     56962
   macro avg       0.63      0.64      0.64     56962
weighted avg       1.00      1.00      1.00     56962

In [ ]:
def evaluate_outlier_classifier(model, data): 
    # Get labels
    labels = model.fit_predict(data)
    # Return inliers
    return data[labels == 0]

In [ ]:
def evaluate_regressor(inliers): 
    X = inliers.drop("sales", axis=1) 
    y = inliers[['sales']]
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)
    
    lr = LinearRegression() 
    lr.fit(X_train, y_train)

    preds = lr.predict(X_test) 
    rmse = root_mean_squared_error(y_test, preds) 
    
    return round(rmse, 3)