# Testing the parsing file by creating a dataframe from it

In [161]:
import pandas as pd

from pathlib import Path
from anomaly_detection.parser.data_parsers import parse_system, parse_security, parse_application

In [162]:
# Path to the data
project_folder = Path.cwd().parent

output_path = project_folder / "data/parsing"

security_evtx_path = project_folder / "data/raw/93_securitelog.evtx"
application_evtx_path = project_folder / "data/raw/93_applog.evtx"
system_evtx_path = project_folder / "data/raw/93_syslog.evtx"

application_evtx_path

WindowsPath('c:/Users/hp/Documents/School/anomaly-detection/data/raw/93_applog.evtx')

# System

In [163]:
system_training_records = parse_system(system_evtx_path)

system_training_records[0]

{'timestamp': {'hour_sin': np.float64(0.8660254037844386),
  'day_sin': np.float64(-0.433883739117558),
  'hour_cos': np.float64(0.5000000000000001),
  'second_cos': np.float64(0.20791169081775943),
  'minute_sin': np.float64(-0.20791169081775898),
  'day_cos': np.float64(-0.9009688679024191),
  'month_cos': np.float64(6.123233995736766e-17),
  'deltatime': Timedelta('0 days 00:02:19.046309'),
  'month_sin': np.float64(1.0),
  'minute_cos': np.float64(0.9781476007338057),
  'second_sin': np.float64(-0.9781476007338056)},
 'profile': {'event_record_id': 210478,
  'execution_thread_id': 5368,
  'version': 0,
  'event_id_frequency': np.float64(0.9060706937218755),
  'event_id': 7036,
  'correlation_activity_id': None,
  'previous_event_id': 7036},
 'data': {'new_value': None,
  'process_name': None,
  'entity': 'Service de transfert intelligent en arrière-plan',
  'context': None,
  'actor': None,
  'old_value': None,
  'status': 'en cours d’exécution',
  'session_id': None}}

In [164]:
flat_system_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in system_training_records]

flat_system_training_record[0]

{'hour_sin': np.float64(0.8660254037844386),
 'day_sin': np.float64(-0.433883739117558),
 'hour_cos': np.float64(0.5000000000000001),
 'second_cos': np.float64(0.20791169081775943),
 'minute_sin': np.float64(-0.20791169081775898),
 'day_cos': np.float64(-0.9009688679024191),
 'month_cos': np.float64(6.123233995736766e-17),
 'deltatime': Timedelta('0 days 00:02:19.046309'),
 'month_sin': np.float64(1.0),
 'minute_cos': np.float64(0.9781476007338057),
 'second_sin': np.float64(-0.9781476007338056),
 'event_record_id': 210478,
 'execution_thread_id': 5368,
 'version': 0,
 'event_id_frequency': np.float64(0.9060706937218755),
 'event_id': 7036,
 'correlation_activity_id': None,
 'previous_event_id': 7036,
 'new_value': None,
 'process_name': None,
 'entity': 'Service de transfert intelligent en arrière-plan',
 'context': None,
 'actor': None,
 'old_value': None,
 'status': 'en cours d’exécution',
 'session_id': None}

In [165]:
system_training_df = pd.DataFrame(flat_system_training_record)

system_training_df.head(10)

,hour_sin,day_sin,hour_cos,second_cos,minute_sin,day_cos,month_cos,deltatime,month_sin,minute_cos,...,correlation_activity_id,previous_event_id,new_value,process_name,entity,context,actor,old_value,status,session_id
0,0.866025,-0.433884,0.500000,0.207912,-0.207912,-0.900969,6.123234e-17,0 days 00:02:19.046309,1.0,0.978148,...,NaN,7036,None,NaN,Service de transfert intelligent en arrière-plan,None,NaN,None,en cours d’exécution,NaN
1,0.866025,-0.433884,0.500000,0.207912,-0.207912,-0.900969,6.123234e-17,0 days 00:00:00.031244,1.0,0.978148,...,NaN,7036,Démarrage automatique,NaN,Service de transfert intelligent en arrière-plan,None,NaN,Démarrage à la demande,None,NaN
2,0.866025,-0.433884,0.500000,0.207912,-0.207912,-0.900969,6.123234e-17,0 days 00:00:00.328128,1.0,0.978148,...,NaN,7040,None,NaN,Carte de performance WMI,None,NaN,None,en cours d’exécution,NaN
3,0.965926,-0.433884,0.258819,0.309017,0.000000,-0.900969,6.123234e-17,0 days 00:02:00.756168,1.0,1.000000,...,NaN,7036,None,NaN,Carte de performance WMI,None,NaN,None,arrêté,NaN
4,0.965926,-0.433884,0.258819,0.309017,0.207912,-0.900969,6.123234e-17,0 days 00:02:00.011128,1.0,0.978148,...,NaN,7036,Démarrage à la demande,NaN,Service de transfert intelligent en arrière-plan,None,NaN,Démarrage automatique,None,NaN
5,0.965926,-0.433884,0.258819,0.309017,0.207912,-0.900969,6.123234e-17,0 days 00:00:00.031255,1.0,0.978148,...,NaN,7040,None,NaN,Service de transfert intelligent en arrière-plan,None,NaN,None,arrêté,NaN
6,0.965926,-0.433884,0.258819,0.978148,0.866025,-0.900969,6.123234e-17,0 days 00:07:14.224809,1.0,0.500000,...,NaN,7036,None,NaN,Service de licences de client (ClipSVC),None,NaN,None,en cours d’exécution,NaN
7,0.965926,-0.433884,0.258819,0.978148,0.866025,-0.900969,6.123234e-17,0 days 00:00:00.109375,1.0,0.500000,...,NaN,7036,None,NaN,Assistant Connexion avec un compte Microsoft,None,NaN,None,en cours d’exécution,NaN
8,0.965926,-0.433884,0.258819,0.978148,0.866025,-0.900969,6.123234e-17,0 days 00:00:00.047848,1.0,0.500000,...,NaN,7036,None,NaN,Optimisation de livraison,None,NaN,None,en cours d’exécution,NaN
9,0.965926,-0.433884,0.258819,0.951057,0.866025,-0.900969,6.123234e-17,0 days 00:00:01.063972,1.0,0.500000,...,NaN,7036,None,NaN,Service de déploiement AppX (AppXSVC),None,NaN,None,en cours d’exécution,NaN

In [166]:
system_encoding_types = [
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Convert to int",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Label encoding",
    "None",
    "Mixed value encoding",
    "One-hot encoding",
    "Entity encoding",
    "Frequency encoding",
    "One-hot encoding",
    "Mixed value encoding",
    "One-hot encoding",
    "None",
]

In [167]:
system_training_summary = pd.DataFrame({
    "column": system_training_df.columns,
    "dtype": system_training_df.dtypes.astype(str),
    "nunique": system_training_df.nunique(dropna=True),
    "nulls": system_training_df.isna().sum(),
    "encoding": system_encoding_types
}).reset_index(drop=True)

system_training_summary.to_csv(output_path / "parsed_system_profile.csv")

system_training_summary

,column,dtype,nunique,nulls,encoding
0,hour_sin,float64,21,0,None
1,day_sin,float64,7,0,None
2,hour_cos,float64,22,0,None
3,second_cos,float64,53,0,None
4,minute_sin,float64,54,0,None
5,day_cos,float64,7,0,None
6,month_cos,float64,4,0,None
7,deltatime,timedelta64[us],47092,0,Convert to int
8,month_sin,float64,4,0,None
9,minute_cos,float64,53,0,None
10,second_sin,float64,54,0,None
11,event_record_id,int64,59779,0,None
12,execution_thread_id,float64,2494,191,None
13,version,float64,3,191,None
14,event_id_frequency,float64,23,0,None
15,event_id,int64,68,0,None
16,correlation_activity_id,str,13,59732,Label encoding
17,previous_event_id,int64,68,0,None
18,new_value,object,72,55015,Mixed value encoding
19,process_name,str,1,59757,One-hot encoding
20,entity,str,238,655,Entity encoding
21,context,object,226,59183,Frequency encoding
22,actor,str,4,59744,One-hot encoding
23,old_value,object,55,55082,Mixed value encoding
24,status,object,3,5603,One-hot encoding
25,session_id,float64,13,59736,None

In [168]:
system_training_df["new_value"].unique()

array([None, 'Démarrage automatique', 'Démarrage à la demande',
       '2026-03-17T16:54:26.904000Z', '2026-03-17T16:55:32.378000Z',
       '2026-03-17T16:56:37.848000Z', '2026-03-17T16:57:43.300000Z',
       '2026-03-17T16:58:48.782000Z', 58372096, 74383360, 18706432,
       '2026-03-24T16:35:02.861000Z', '2026-03-31T08:52:53.708112Z',
       '2026-03-31T08:53:06.500000Z', 0, '2036-08-31T17:15:55.000000Z',
       '2034-08-13T15:30:12.000000Z', '2020-02-27T12:02:34.000000Z',
       '2025-12-19T13:34:47.000000Z', '2037-02-23T07:11:04.000000Z',
       76955648, '1979-05-17T15:12:11.000000Z',
       '2023-05-26T09:16:28.000000Z', '2067-10-28T18:00:57.000000Z',
       '2004-08-10T17:55:11.000000Z', '2026-03-31T14:51:55.596191Z',
       '2026-03-31T14:52:08.500000Z', 59830272, 11456512, 3919872,
       55885824, 74080256, 18710528, '2026-04-15T14:52:43.072000Z',
       '2026-04-15T22:21:49.908481Z', '2026-04-15T22:21:59.500000Z',
       76873728, '2076-07-03T06:42:35.000000Z',
       '2026-04-15T22:22:16.479000Z', '1976-12-03T08:55:05.000000Z',
       '2085-11-15T11:15:36.000000Z', '2026-04-16T13:47:16.993746Z',
       '2026-04-16T13:47:26.500000Z', '2026-04-16T13:47:40.531000Z',
       11460608, '2026-04-17T07:43:11.749087Z',
       '2026-04-17T07:43:21.500000Z', '2026-04-17T07:43:34.249000Z',
       '2026-04-24T15:55:37.311000Z', '2026-04-24T15:56:42.382000Z',
       '2026-04-24T15:57:47.451000Z', '2026-04-24T15:58:52.519000Z',
       '2026-04-30T08:03:35.218032Z', 74424320, 18812928, 74428416,
       18849792, 77176832, 18866176, '2026-05-21T16:31:52.731000Z',
       '2026-05-21T22:26:43.334240Z', '2026-05-21T22:27:00.500000Z',
       '2026-07-12T01:54:48.000000Z', 77271040,
       '2048-04-27T00:51:47.000000Z', 73965568, 3944448, 57176064,
       74235904, 18722816, '2026-03-12T14:55:36.000000Z', 74268672,
       18800640], dtype=object)

In [169]:
system_training_df["entity"].unique()

<StringArray>
[                     'Service de transfert intelligent en arrière-plan',
                                              'Carte de performance WMI',
                               'Service de licences de client (ClipSVC)',
                          'Assistant Connexion avec un compte Microsoft',
                                             'Optimisation de livraison',
                                 'Service de déploiement AppX (AppXSVC)',
                     'Programme d’installation pour les modules Windows',
                                                        'Windows Update',
                                                 'Protection logicielle',
                                       'Service Configuration du réseau',
 ...
                                        '\??\C:\Users\Akorbi\ntuser.dat',
                                        '\??\C:\Users\bayrem\ntuser.dat',
                                      '\??\C:\Users\chahbani\ntuser.dat',
 'Service pour utilisateur de plateforme d’appareils connectés_3e257675',
            'Service utilisateur de notifications Push Windows_3e257675',
                                  'Backup Exec Remote Agent for Windows',
             'Service utilisateur de notifications Push Windows_1e0cc7a',
  'Service pour utilisateur de plateforme d’appareils connectés_1e0cc7a',
            'Service utilisateur de notifications Push Windows_7903e430',
 'Service pour utilisateur de plateforme d’appareils connectés_7903e430']
Length: 239, dtype: str

In [170]:
system_training_df["context"].unique()

array([None, ' |  |  |  | 1468229 | 60 | -60 Paris, Madrid', '',
       ' |  |  |  | 1554628 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1554629 | 60 | -60 Paris, Madrid', 947,
       ' |  |  |  | 1641029 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1727428 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1727429 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1813829 | 60 | -60 Paris, Madrid', 1,
       ' |  |  |  | 1900200 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1900202 | 60 | -60 Paris, Madrid', 4,
       ' |  |  |  | 1986602 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1986603 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2073002 | 60 | -60 Paris, Madrid', 84, 232, 81,
       ' |  |  |  | 2159401 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2159402 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2245802 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2332201 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2332202 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2418602 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2418603 | 60 | -60 Paris, Madrid', 3, 2,
       ' |  |  |  | 2504606 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2591005 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2591006 | 60 | -60 Paris, Madrid', 104075,
       ' |  |  |  | 2677406 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2677407 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2763806 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2850205 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2850206 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2936606 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2936607 | 60 | -60 Paris, Madrid', 452, 36, 991, 656,
       0, '0x0', '6.1', '6.0', 5, 6, 7, 8, 9, 10, 11, 83, 89, 105, 56,
       ' |  |  |  | 17 | 60 | -60 Paris, Madrid', 1255,
       'Under Observation - More Data Needed',
       ' |  |  |  | 7613 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 7614 | 60 | -60 Paris, Madrid', 475, 34,
       ' |  |  |  | 22 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 72470 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 72472 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 158871 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 245271 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 245272 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 331671 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 418070 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 418071 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 504471 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 504472 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 590871 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 677271 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 677272 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 763671 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 763672 | 60 | -60 Paris, Madrid', 15316,
       ' |  |  |  | 850071 | 60 | -60 Paris, Madrid', 241,
       ' |  |  |  | 936471 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 936472 | 60 | -60 Paris, Madrid', 20704,
       ' |  |  |  | 1022871 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1022872 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1109271 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1195671 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1195672 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1282071 | 60 | -60 Paris, Madrid', 888, 418, 1246,
       324, 91, 102, 58, ' |  |  |  | 16 | 60 | -60 Paris, Madrid', 687,
       685, ' |  |  |  | 45479 | 60 | -60 Paris, Madrid', 35,
       ' |  |  |  | 13 | 60 | -60 Paris, Madrid', 160535,
       ' |  |  |  | 11798 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 98198 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 98199 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 184598 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 270998 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 270999 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 357398 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 443797 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 443798 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 530198 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 530199 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 616598 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 702981 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 789377 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 789378 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 875777 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 875778 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 962177 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 962178 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1048578 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1134977 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1134978 | 60 | -60 Paris, Madrid', 406, 235, 104160,
       ' |  |  |  | 1221378 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1307777 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1307778 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1394177 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1394178 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1480578 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1480579 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1566978 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1653377 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1653378 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1739777 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1739778 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1826177 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1826178 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1912578 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1998977 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1998978 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2085377 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2085378 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2171777 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2171778 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2258178 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2344577 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2344578 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2430977 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2430978 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2517377 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2517378 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2603778 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2690177 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2690178 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2776577 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2776578 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2862977 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2862978 | 60 | -60 Paris, Madrid', 243,
       ' |  |  |  | 2949377 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2949378 | 60 | -60 Paris, Madrid', 946, 574, 1265,
       801, ' |  |  |  | 45179 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 45180 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 131579 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 217978 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 217979 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 304379 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 304380 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 390779 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 390780 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 477179 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 563578 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 563579 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 649979 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 649980 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 736379 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 736380 | 60 | -60 Paris, Madrid', 234, 20784,
       ' |  |  |  | 822779 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 909178 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 909179 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 995579 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 995580 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1081979 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1081980 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1168379 | 60 | -60 Paris, Madrid', 103333,
       ' |  |  |  | 1254778 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1254779 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1341178 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1341179 | 60 | -60 Paris, Madrid', 955,
       ' |  |  |  | 1427579 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1427580 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1513979 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1513980 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1600379 | 60 | -60 Paris, Madrid', 313,
       ' |  |  |  | 1686778 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1686779 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1773179 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1773180 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1859579 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1859580 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 1945979 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2032378 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2032379 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2118779 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2118780 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2205179 | 60 | -60 Paris, Madrid',
       ' |  |  |  | 2205180 | 60 | -60 Paris, Madrid', 481], dtype=object)

# Application

In [171]:
application_training_records = parse_application(application_evtx_path)

application_training_records[0]

{'timestamp': {'hour_sin': np.float64(0.49999999999999994),
  'day_sin': np.float64(-0.433883739117558),
  'hour_cos': np.float64(-0.8660254037844387),
  'second_cos': np.float64(1.0),
  'minute_sin': np.float64(-0.40673664307580015),
  'day_cos': np.float64(-0.9009688679024191),
  'month_cos': np.float64(-1.0),
  'deltatime': Timedelta('0 days 00:00:20.289018'),
  'month_sin': np.float64(1.2246467991473532e-16),
  'minute_cos': np.float64(0.913545457642601),
  'second_sin': np.float64(0.0)},
 'profile': {'event_record_id': 2899035,
  'execution_thread_id': None,
  'version': None,
  'event_id_frequency': np.float64(0.9653113448962184),
  'event_id': 4,
  'correlation_activity_id': None,
  'previous_event_id': 4},
 'data': {'entity': None,
  'context': 'php[8696] | PHP Warning: PHP Startup: Unable to load dynamic library \'php_pdo_sqlsrv_74_ts_x64.dll\' (tried: c:/wamp/bin/php/php7.4.0/ext/php_pdo_sqlsrv_74_ts_x64.dll (%1 n’est pas une application Win32 valide.), c:/wamp/bin/php/php7.4.0/ext/php_php_pdo_sqlsrv_74_ts_x64.dll.dll (Le module spécifié est introuvable.)) (php  "C:\\wamp\\www\\CARTENET\\library\\App\\Jobs\\Ckeckifsigned.php")'}}

In [172]:
flat_application_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in application_training_records]

flat_application_training_record[0]

{'hour_sin': np.float64(0.49999999999999994),
 'day_sin': np.float64(-0.433883739117558),
 'hour_cos': np.float64(-0.8660254037844387),
 'second_cos': np.float64(1.0),
 'minute_sin': np.float64(-0.40673664307580015),
 'day_cos': np.float64(-0.9009688679024191),
 'month_cos': np.float64(-1.0),
 'deltatime': Timedelta('0 days 00:00:20.289018'),
 'month_sin': np.float64(1.2246467991473532e-16),
 'minute_cos': np.float64(0.913545457642601),
 'second_sin': np.float64(0.0),
 'event_record_id': 2899035,
 'execution_thread_id': None,
 'version': None,
 'event_id_frequency': np.float64(0.9653113448962184),
 'event_id': 4,
 'correlation_activity_id': None,
 'previous_event_id': 4,
 'entity': None,
 'context': 'php[8696] | PHP Warning: PHP Startup: Unable to load dynamic library \'php_pdo_sqlsrv_74_ts_x64.dll\' (tried: c:/wamp/bin/php/php7.4.0/ext/php_pdo_sqlsrv_74_ts_x64.dll (%1 n’est pas une application Win32 valide.), c:/wamp/bin/php/php7.4.0/ext/php_php_pdo_sqlsrv_74_ts_x64.dll.dll (Le module spécifié est introuvable.)) (php  "C:\\wamp\\www\\CARTENET\\library\\App\\Jobs\\Ckeckifsigned.php")'}

In [173]:
application_training_df = pd.DataFrame(flat_application_training_record)

application_training_df.head(10)

,hour_sin,day_sin,hour_cos,second_cos,minute_sin,day_cos,month_cos,deltatime,month_sin,minute_cos,second_sin,event_record_id,execution_thread_id,version,event_id_frequency,event_id,correlation_activity_id,previous_event_id,entity,context
0,0.5,-0.433884,-0.866025,1.000000,-0.406737,-0.900969,-1.0,0 days 00:00:20.289018,1.224647e-16,0.913545,0.000000,2899035,NaN,NaN,0.965311,4,None,4,NaN,php[8696] | PHP Warning: PHP Startup: Unable t...
1,0.5,-0.433884,-0.866025,0.951057,-0.406737,-0.900969,-1.0,0 days 00:00:02.662888,1.224647e-16,0.913545,0.309017,2899036,NaN,NaN,0.965311,4,None,4,NaN,php[8736] | PHP Warning: PHP Startup: Unable t...
2,0.5,-0.433884,-0.866025,0.951057,-0.406737,-0.900969,-1.0,0 days 00:00:00.062795,1.224647e-16,0.913545,0.309017,2899037,NaN,NaN,0.965311,4,None,4,NaN,php[8456] | PHP Warning: PHP Startup: Unable t...
3,0.5,-0.433884,-0.866025,0.951057,-0.406737,-0.900969,-1.0,0 days 00:00:00,1.224647e-16,0.913545,0.309017,2899038,NaN,NaN,0.965311,4,None,4,NaN,php[4500] | PHP Warning: PHP Startup: Unable t...
4,0.5,-0.433884,-0.866025,0.951057,-0.406737,-0.900969,-1.0,0 days 00:00:00.015626,1.224647e-16,0.913545,0.309017,2899039,NaN,NaN,0.965311,4,None,4,NaN,php[3664] | PHP Warning: PHP Startup: Unable t...
5,0.5,-0.433884,-0.866025,1.000000,-0.207912,-0.900969,-1.0,0 days 00:01:57.258522,1.224647e-16,0.978148,0.000000,2899040,NaN,NaN,0.965311,4,None,4,NaN,php[1176] | PHP Warning: PHP Startup: Unable t...
6,0.5,-0.433884,-0.866025,0.951057,-0.207912,-0.900969,-1.0,0 days 00:00:02.284295,1.224647e-16,0.978148,0.309017,2899041,NaN,NaN,0.965311,4,None,4,NaN,php[3704] | PHP Warning: PHP Startup: Unable t...
7,0.5,-0.433884,-0.866025,0.951057,-0.207912,-0.900969,-1.0,0 days 00:00:00,1.224647e-16,0.978148,0.309017,2899042,NaN,NaN,0.965311,4,None,4,NaN,php[3664] | PHP Warning: PHP Startup: Unable t...
8,0.5,-0.433884,-0.866025,0.951057,-0.207912,-0.900969,-1.0,0 days 00:00:00.015627,1.224647e-16,0.978148,0.309017,2899043,NaN,NaN,0.965311,4,None,4,NaN,php[8788] | PHP Warning: PHP Startup: Unable t...
9,0.5,-0.433884,-0.866025,0.951057,-0.207912,-0.900969,-1.0,0 days 00:00:00.015624,1.224647e-16,0.978148,0.309017,2899044,NaN,NaN,0.965311,4,None,4,NaN,php[7804] | PHP Warning: PHP Startup: Unable t...

In [174]:
application_encoding_types = [
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Convert to int",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Label encoding",
    "None",
    "One-hot encoding",
    "Embedding encoding"
]

In [175]:
application_training_summary = pd.DataFrame({
    "column": application_training_df.columns,
    "dtype": application_training_df.dtypes.astype(str),
    "nunique": application_training_df.nunique(dropna=True),
    "nulls": application_training_df.isna().sum(),
    "encoding": application_encoding_types
}).reset_index(drop=True)

application_training_summary.to_csv(output_path / "parsed_application_profile.csv")

application_training_summary

,column,dtype,nunique,nulls,encoding
0,hour_sin,float64,21,0,None
1,day_sin,float64,6,0,None
2,hour_cos,float64,22,0,None
3,second_cos,float64,53,0,None
4,minute_sin,float64,51,0,None
5,day_cos,float64,6,0,None
6,month_cos,float64,1,0,None
7,deltatime,timedelta64[us],9808,0,Convert to int
8,month_sin,float64,1,0,None
9,minute_cos,float64,51,0,None
10,second_sin,float64,54,0,None
11,event_record_id,int64,21102,0,None
12,execution_thread_id,float64,1,20551,None
13,version,float64,1,20551,None
14,event_id_frequency,float64,8,0,None
15,event_id,int64,10,0,None
16,correlation_activity_id,object,0,21102,Label encoding
17,previous_event_id,int64,10,0,None
18,entity,str,3,21057,One-hot encoding
19,context,str,6884,15,Embedding encoding

In [176]:
application_training_df['entity'].unique()

<StringArray>
[                                                          nan,
 '86 3b a2 db 28 07 24 23 98 c4 c9 49 00 04 e3 ac 6a 43 69 38',
 '36 a0 aa 09 0f e7 1c 4d 1b 51 87 5f 1c 5a 21 d5 60 c5 93 b5',
 '11 78 48 a9 83 4d 40 17 06 34 11 55 68 fb ad 55 1b a2 0c bf']
Length: 4, dtype: str

# Security

In [177]:
security_training_records = parse_security(security_evtx_path)

security_training_records[0]

{'timestamp': {'hour_sin': np.float64(0.0),
  'day_sin': np.float64(0.9749279121818236),
  'hour_cos': np.float64(1.0),
  'second_cos': np.float64(0.7431448254773942),
  'minute_sin': np.float64(1.0),
  'day_cos': np.float64(-0.22252093395631434),
  'month_cos': np.float64(-1.0),
  'deltatime': Timedelta('0 days 00:00:01.096741'),
  'month_sin': np.float64(1.2246467991473532e-16),
  'minute_cos': np.float64(2.83276944882399e-16),
  'second_sin': np.float64(0.6691306063588582)},
 'profile': {'event_record_id': 34978816,
  'execution_thread_id': 5960,
  'version': 2,
  'event_id_frequency': np.float64(0.20136019830928623),
  'event_id': 4624,
  'correlation_activity_id': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01',
  'previous_event_id': 4624},
 'data': {'process_name': 'C:\\Windows\\System32\\svchost.exe',
  'entity': 'S-1-5-21-3333335972-2113272682-612058519-500',
  'context': 4,
  'actor': 'S-1-5-18',
  'value': None,
  'ip': '-',
  'status': None,
  'logon_id': '0x3e7',
  'process_id': None,
  'permission': 'Negotiate'}}

In [178]:
flat_security_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in security_training_records]

flat_security_training_record[0]

{'hour_sin': np.float64(0.0),
 'day_sin': np.float64(0.9749279121818236),
 'hour_cos': np.float64(1.0),
 'second_cos': np.float64(0.7431448254773942),
 'minute_sin': np.float64(1.0),
 'day_cos': np.float64(-0.22252093395631434),
 'month_cos': np.float64(-1.0),
 'deltatime': Timedelta('0 days 00:00:01.096741'),
 'month_sin': np.float64(1.2246467991473532e-16),
 'minute_cos': np.float64(2.83276944882399e-16),
 'second_sin': np.float64(0.6691306063588582),
 'event_record_id': 34978816,
 'execution_thread_id': 5960,
 'version': 2,
 'event_id_frequency': np.float64(0.20136019830928623),
 'event_id': 4624,
 'correlation_activity_id': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01',
 'previous_event_id': 4624,
 'process_name': 'C:\\Windows\\System32\\svchost.exe',
 'entity': 'S-1-5-21-3333335972-2113272682-612058519-500',
 'context': 4,
 'actor': 'S-1-5-18',
 'value': None,
 'ip': '-',
 'status': None,
 'logon_id': '0x3e7',
 'process_id': None,
 'permission': 'Negotiate'}

In [179]:
security_training_df = pd.DataFrame(flat_security_training_record)

security_training_df.head(10)

,hour_sin,day_sin,hour_cos,second_cos,minute_sin,day_cos,month_cos,deltatime,month_sin,minute_cos,...,process_name,entity,context,actor,value,ip,status,logon_id,process_id,permission
0,0.0,0.974928,1.0,0.743145,1.000000,-0.222521,-1.0,0 days 00:00:01.096741,1.224647e-16,2.832769e-16,...,C:\Windows\System32\svchost.exe,S-1-5-21-3333335972-2113272682-612058519-500,4,S-1-5-18,None,-,NaN,0x3e7,None,Negotiate
1,0.0,0.974928,1.0,0.743145,1.000000,-0.222521,-1.0,0 days 00:00:00.000008,1.224647e-16,2.832769e-16,...,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,NaN,None,NaN,NaN,0x77061c91,None,SeSecurityPrivilege\r\n\t\t\tSeTakeOwnershipPr...
2,0.0,0.974928,1.0,0.669131,1.000000,-0.222521,-1.0,0 days 00:00:00.671212,1.224647e-16,2.832769e-16,...,NaN,S-1-5-21-3333335972-2113272682-612058519-500,4,NaN,None,NaN,NaN,0x77061c91,None,NaN
3,0.0,0.974928,1.0,0.866025,1.000000,-0.222521,-1.0,0 days 00:00:46.664296,1.224647e-16,2.832769e-16,...,NaN,S-1-5-21-3333335972-2113272682-612058519-500,4,NaN,None,NaN,NaN,0x770579fb,None,NaN
4,0.0,0.974928,1.0,1.000000,0.994522,-0.222521,-1.0,0 days 00:00:05.480553,1.224647e-16,-1.045285e-01,...,NaN,Administrateur,None,NaN,None,NaN,0x0,NaN,None,NaN
5,0.0,0.974928,1.0,1.000000,0.994522,-0.222521,-1.0,0 days 00:00:00.000708,1.224647e-16,-1.045285e-01,...,C:\Windows\System32\svchost.exe,Administrateur,localhost,S-1-5-18,None,-,NaN,0x3e7,None,NaN
6,0.0,0.974928,1.0,1.000000,0.994522,-0.222521,-1.0,0 days 00:00:00.000026,1.224647e-16,-1.045285e-01,...,C:\Windows\System32\svchost.exe,S-1-5-21-3333335972-2113272682-612058519-500,4,S-1-5-18,None,-,NaN,0x3e7,None,Negotiate
7,0.0,0.974928,1.0,1.000000,0.994522,-0.222521,-1.0,0 days 00:00:00.000008,1.224647e-16,-1.045285e-01,...,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,NaN,None,NaN,NaN,0x77067629,None,SeSecurityPrivilege\r\n\t\t\tSeTakeOwnershipPr...
8,0.0,0.974928,1.0,0.978148,0.994522,-0.222521,-1.0,0 days 00:00:02.147107,1.224647e-16,-1.045285e-01,...,NaN,Administrateur,None,NaN,None,NaN,0x0,NaN,None,NaN
9,0.0,0.974928,1.0,0.978148,0.994522,-0.222521,-1.0,0 days 00:00:00.001451,1.224647e-16,-1.045285e-01,...,NaN,Administrateur,None,NaN,None,NaN,0x0,NaN,None,NaN

In [180]:
security_encoding_types = [
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Convert to int",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Label encoding",
    "None",
    "Label encoding",
    "Label encoding",
    "Label encoding",
    "One-hot encoding",
    "XML presence encoding",
    "IP address encoding",
    "One-hot encoding",
    "Hex to int encoding",
    "Hex to int encoding",
    "Label encoding"
]

In [181]:
security_training_summary = pd.DataFrame({
    "column": security_training_df.columns,
    "dtype": security_training_df.dtypes.astype(str),
    "nunique": security_training_df.nunique(dropna=True),
    "nulls": security_training_df.isna().sum(),
    "encoding": security_encoding_types
}).reset_index(drop=True)

security_training_summary.to_csv(output_path / "parsed_security_profile.csv")

security_training_summary

,column,dtype,nunique,nulls,encoding
0,hour_sin,float64,8,0,None
1,day_sin,float64,1,0,None
2,hour_cos,float64,10,0,None
3,second_cos,float64,51,0,None
4,minute_sin,float64,52,0,None
5,day_cos,float64,1,0,None
6,month_cos,float64,1,0,None
7,deltatime,timedelta64[us],8450,0,Convert to int
8,month_sin,float64,1,0,None
9,minute_cos,float64,51,0,None
10,second_sin,float64,53,0,None
11,event_record_id,int64,31466,0,None
12,execution_thread_id,int64,171,0,None
13,version,int64,3,0,None
14,event_id_frequency,float64,12,0,None
15,event_id,int64,17,0,None
16,correlation_activity_id,str,6186,6197,Label encoding
17,previous_event_id,int64,17,0,None
18,process_name,str,5,18941,Label encoding
19,entity,str,44,3,Label encoding
20,context,object,12,12692,Label encoding
21,actor,str,6,18717,One-hot encoding
22,value,object,42,31371,XML presence encoding
23,ip,str,3,18941,IP address encoding
24,status,str,1,25281,One-hot encoding
25,logon_id,str,6204,6200,Hex to int encoding
26,process_id,object,63,31256,Hex to int encoding
27,permission,str,9,18784,Label encoding

In [182]:
security_training_df['context'].unique()

array([4, None, 'localhost', 5, 3, 'Object Access', 'esante$', '%%8100',
       2, 10, '%%2458', '%%2480', '%%2464'], dtype=object)

In [183]:
security_training_df['value'].unique()

array([None,
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>Microsoft Corporation.</Source>\r\n    <Author>Microsoft Corporation.</Author>\r\n    <Description>Cette tâche permet de démarrer le service Windows Update lorsque des opérations planifiées, comme des analyses, doivent être effectuées.</Description>\r\n    <URI>\\Microsoft\\Windows\\WindowsUpdate\\Scheduled Start</URI>\r\n    <SecurityDescriptor>D:(A;;FA;;;SY)(A;;FRFX;;;LS)(A;;FA;;;BA)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <TimeTrigger>\r\n      <StartBoundary>2026-06-17T17:15:29Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <RandomDelay>PT1M</RandomDelay>\r\n    </TimeTrigger>\r\n    <SessionStateChangeTrigger>\r\n      <Enabled>false</Enabled>\r\n      <StateChange>ConsoleDisconnect</StateChange>\r\n    </SessionStateChangeTrigger>\r\n    <SessionStateChangeTrigger>\r\n      <Enabled>false</Enabled>\r\n      <StateChange>RemoteDisconnect</StateChange>\r\n    </SessionStateChangeTrigger>\r\n    <WnfStateChangeTrigger>\r\n      <Enabled>false</Enabled>\r\n      <StateName>7508BCA3380C960C</StateName>\r\n      <Data>01</Data>\r\n      <DataOffset>0</DataOffset>\r\n    </WnfStateChangeTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="LocalSystem">\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n      <UserId>NT AUTHORITY\\SYSTEM</UserId>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>true</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <Duration>PT10M</Duration>\r\n      <WaitTimeout>PT1H</WaitTimeout>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>false</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>false</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n  </Settings>\r\n  <Actions Context="LocalSystem">\r\n    <Exec>\r\n      <Command>C:\\WINDOWS\\system32\\sc.exe</Command>\r\n      <Arguments>start wuauserv</Arguments>\r\n    </Exec>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T01:12:55Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T01:42:55Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.3" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Author>ESANTE\\Administrateur</Author>\r\n    <Description>Met à jour les flux système obsolètes.</Description>\r\n    <URI>\\User_Feed_Synchronization-{2BA688E8-D52A-4E7D-AFD8-2070D64559BD}</URI>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2026-06-17T08:22:50Z</StartBoundary>\r\n      <EndBoundary>2036-06-17T08:22:50Z</EndBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="Author">\r\n      <UserId>S-1-5-21-3333335972-2113272682-612058519-500</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n      <LogonType>InteractiveToken</LogonType>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>true</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <Duration>PT10M</Duration>\r\n      <WaitTimeout>PT1H</WaitTimeout>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n  </Settings>\r\n  <Actions Context="Author">\r\n    <Exec>\r\n      <Command>C:\\WINDOWS\\system32\\msfeedssync.exe</Command>\r\n      <Arguments>sync</Arguments>\r\n    </Exec>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T02:12:55Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Version>1.0</Version>\r\n    <URI>\\Microsoft\\Windows\\Device Information\\Device</URI>\r\n    <SecurityDescriptor>D:(A;;GA;;;BA)(A;;GA;;;SY)(A;;FRFX;;;LS)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <TimeTrigger>\r\n      <Repetition>\r\n        <Interval>P1D</Interval>\r\n        <StopAtDurationEnd>false</StopAtDurationEnd>\r\n      </Repetition>\r\n      <StartBoundary>2008-09-01T03:00:00</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <RandomDelay>PT2H</RandomDelay>\r\n    </TimeTrigger>\r\n    <WnfStateChangeTrigger id="WNF_DEP_OOBE_COMPLETE">\r\n      <Enabled>false</Enabled>\r\n      <StateName>750CBCA3290B9641</StateName>\r\n      <Data>01</Data>\r\n      <DataOffset>0</DataOffset>\r\n    </WnfStateChangeTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="LocalSystem">\r\n      <UserId>S-1-5-18</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>true</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>false</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>P4D</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n  </Settings>\r\n  <Actions Context="LocalSystem">\r\n    <Exec>\r\n      <Command>%windir%\\system32\\devicecensus.exe</Command>\r\n    </Exec>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T02:41:58Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T02:43:17Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',