# Testing the parsing file by creating a dataframe from it

In [94]:
import pandas as pd

from pathlib import Path
from anomaly_detection.parser.data_parsers import parse_system, parse_security, parse_application

In [95]:
# Path to the data
project_folder = Path.cwd().parent

output_path = project_folder / "data/parsing"

security_evtx_path = project_folder / "data/raw/93_securitelog.evtx"
application_evtx_path = project_folder / "data/raw/93_applog.evtx"
system_evtx_path = project_folder / "data/raw/93_syslog.evtx"

application_evtx_path

WindowsPath('c:/Users/hp/Documents/School/anomaly-detection/data/raw/93_applog.evtx')

# System

In [96]:
system_training_records = parse_system(system_evtx_path)

system_training_records[0]

{'timestamp': {'month_sin': np.float64(1.0),
  'second_sin': np.float64(-0.9781476007338056),
  'hour_sin': np.float64(0.8660254037844386),
  'minute_cos': np.float64(0.9781476007338057),
  'minute_sin': np.float64(-0.20791169081775898),
  'deltatime': Timedelta('0 days 00:02:19.046309'),
  'day_cos': np.float64(-0.9009688679024191),
  'hour_cos': np.float64(0.5000000000000001),
  'month_cos': np.float64(6.123233995736766e-17),
  'second_cos': np.float64(0.20791169081775943),
  'day_sin': np.float64(-0.433883739117558)},
 'profile': {'execution_thread_id': 5368,
  'event_id_frequency': np.float64(0.9060706937218755),
  'correlation_activity_id': None,
  'previous_event_id': 7036,
  'event_id': 7036,
  'version': 0,
  'event_record_id': 210478},
 'data': {'status': 'en cours d’exécution',
  'process_name': None,
  'entity': 'Service de transfert intelligent en arrière-plan',
  'session_id': None,
  'old_value': None,
  'new_value': None,
  'actor': None,
  'context': None}}

In [97]:
flat_system_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in system_training_records]

flat_system_training_record[0]

{'month_sin': np.float64(1.0),
 'second_sin': np.float64(-0.9781476007338056),
 'hour_sin': np.float64(0.8660254037844386),
 'minute_cos': np.float64(0.9781476007338057),
 'minute_sin': np.float64(-0.20791169081775898),
 'deltatime': Timedelta('0 days 00:02:19.046309'),
 'day_cos': np.float64(-0.9009688679024191),
 'hour_cos': np.float64(0.5000000000000001),
 'month_cos': np.float64(6.123233995736766e-17),
 'second_cos': np.float64(0.20791169081775943),
 'day_sin': np.float64(-0.433883739117558),
 'execution_thread_id': 5368,
 'event_id_frequency': np.float64(0.9060706937218755),
 'correlation_activity_id': None,
 'previous_event_id': 7036,
 'event_id': 7036,
 'version': 0,
 'event_record_id': 210478,
 'status': 'en cours d’exécution',
 'process_name': None,
 'entity': 'Service de transfert intelligent en arrière-plan',
 'session_id': None,
 'old_value': None,
 'new_value': None,
 'actor': None,
 'context': None}

In [98]:
system_training_df = pd.DataFrame(flat_system_training_record)

system_training_df.head(10)

,month_sin,second_sin,hour_sin,minute_cos,minute_sin,deltatime,day_cos,hour_cos,month_cos,second_cos,...,version,event_record_id,status,process_name,entity,session_id,old_value,new_value,actor,context
0,1.0,-0.978148,0.866025,0.978148,-0.207912,0 days 00:02:19.046309,-0.900969,0.500000,6.123234e-17,0.207912,...,0.0,210478,en cours d’exécution,NaN,Service de transfert intelligent en arrière-plan,NaN,None,None,NaN,None
1,1.0,-0.978148,0.866025,0.978148,-0.207912,0 days 00:00:00.031244,-0.900969,0.500000,6.123234e-17,0.207912,...,0.0,210479,None,NaN,Service de transfert intelligent en arrière-plan,NaN,Démarrage à la demande,Démarrage automatique,NaN,None
2,1.0,-0.978148,0.866025,0.978148,-0.207912,0 days 00:00:00.328128,-0.900969,0.500000,6.123234e-17,0.207912,...,0.0,210480,en cours d’exécution,NaN,Carte de performance WMI,NaN,None,None,NaN,None
3,1.0,-0.951057,0.965926,1.000000,0.000000,0 days 00:02:00.756168,-0.900969,0.258819,6.123234e-17,0.309017,...,0.0,210481,arrêté,NaN,Carte de performance WMI,NaN,None,None,NaN,None
4,1.0,-0.951057,0.965926,0.978148,0.207912,0 days 00:02:00.011128,-0.900969,0.258819,6.123234e-17,0.309017,...,0.0,210482,None,NaN,Service de transfert intelligent en arrière-plan,NaN,Démarrage automatique,Démarrage à la demande,NaN,None
5,1.0,-0.951057,0.965926,0.978148,0.207912,0 days 00:00:00.031255,-0.900969,0.258819,6.123234e-17,0.309017,...,0.0,210483,arrêté,NaN,Service de transfert intelligent en arrière-plan,NaN,None,None,NaN,None
6,1.0,0.207912,0.965926,0.500000,0.866025,0 days 00:07:14.224809,-0.900969,0.258819,6.123234e-17,0.978148,...,0.0,210484,en cours d’exécution,NaN,Service de licences de client (ClipSVC),NaN,None,None,NaN,None
7,1.0,0.207912,0.965926,0.500000,0.866025,0 days 00:00:00.109375,-0.900969,0.258819,6.123234e-17,0.978148,...,0.0,210485,en cours d’exécution,NaN,Assistant Connexion avec un compte Microsoft,NaN,None,None,NaN,None
8,1.0,0.207912,0.965926,0.500000,0.866025,0 days 00:00:00.047848,-0.900969,0.258819,6.123234e-17,0.978148,...,0.0,210486,en cours d’exécution,NaN,Optimisation de livraison,NaN,None,None,NaN,None
9,1.0,0.309017,0.965926,0.500000,0.866025,0 days 00:00:01.063972,-0.900969,0.258819,6.123234e-17,0.951057,...,0.0,210487,en cours d’exécution,NaN,Service de déploiement AppX (AppXSVC),NaN,None,None,NaN,None

In [99]:
system_encoding_types = [
    "None",
    "None",
    "None",
    "None",
    "None",
    "Convert to int",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Presence encoding",
    "None",
    "None",
    "None",
    "None",
    "Mixed value encoding",
    "One-hot encoding",
    "Entity encoding",
    "Frequency encoding",
    "One-hot encoding",
    "Mixed value encoding",
    "One-hot encoding",
    "None",
]

In [100]:
system_training_summary = pd.DataFrame({
    "column": system_training_df.columns,
    "dtype": system_training_df.dtypes.astype(str),
    "nunique": system_training_df.nunique(dropna=True),
    "nulls": system_training_df.isna().sum(),
    "encoding": system_encoding_types
}).reset_index(drop=True)

system_training_summary.to_csv(output_path / "parsed_system_profile.csv")

system_training_summary

,column,dtype,nunique,nulls,encoding
0,month_sin,float64,4,0,None
1,second_sin,float64,54,0,None
2,hour_sin,float64,21,0,None
3,minute_cos,float64,53,0,None
4,minute_sin,float64,54,0,None
5,deltatime,timedelta64[us],47092,0,Convert to int
6,day_cos,float64,7,0,None
7,hour_cos,float64,22,0,None
8,month_cos,float64,4,0,None
9,second_cos,float64,53,0,None
10,day_sin,float64,7,0,None
11,execution_thread_id,float64,2494,191,None
12,event_id_frequency,float64,23,0,None
13,correlation_activity_id,str,13,59732,Presence encoding
14,previous_event_id,int64,68,0,None
15,event_id,int64,68,0,None
16,version,float64,3,191,None
17,event_record_id,int64,59779,0,None
18,status,object,3,5603,Mixed value encoding
19,process_name,str,1,59757,One-hot encoding
20,entity,str,238,655,Entity encoding
21,session_id,float64,13,59736,Frequency encoding
22,old_value,object,55,55082,One-hot encoding
23,new_value,object,72,55015,Mixed value encoding
24,actor,str,4,59744,One-hot encoding
25,context,object,226,59183,None

In [101]:
system_training_df["new_value"].unique()

array([None, 'Démarrage automatique', 'Démarrage à la demande',
       '2026-03-17T16:54:26.904000Z', '2026-03-17T16:55:32.378000Z',
       '2026-03-17T16:56:37.848000Z', '2026-03-17T16:57:43.300000Z',
       '2026-03-17T16:58:48.782000Z', 58372096, 74383360, 18706432,
       '2026-03-24T16:35:02.861000Z', '2026-03-31T08:52:53.708112Z',
       '2026-03-31T08:53:06.500000Z', 0, '2036-08-31T17:15:55.000000Z',
       '2034-08-13T15:30:12.000000Z', '2020-02-27T12:02:34.000000Z',
       '2025-12-19T13:34:47.000000Z', '2037-02-23T07:11:04.000000Z',
       76955648, '1979-05-17T15:12:11.000000Z',
       '2023-05-26T09:16:28.000000Z', '2067-10-28T18:00:57.000000Z',
       '2004-08-10T17:55:11.000000Z', '2026-03-31T14:51:55.596191Z',
       '2026-03-31T14:52:08.500000Z', 59830272, 11456512, 3919872,
       55885824, 74080256, 18710528, '2026-04-15T14:52:43.072000Z',
       '2026-04-15T22:21:49.908481Z', '2026-04-15T22:21:59.500000Z',
       76873728, '2076-07-03T06:42:35.000000Z',
       '2026-04-15T22:22:16.479000Z', '1976-12-03T08:55:05.000000Z',
       '2085-11-15T11:15:36.000000Z', '2026-04-16T13:47:16.993746Z',
       '2026-04-16T13:47:26.500000Z', '2026-04-16T13:47:40.531000Z',
       11460608, '2026-04-17T07:43:11.749087Z',
       '2026-04-17T07:43:21.500000Z', '2026-04-17T07:43:34.249000Z',
       '2026-04-24T15:55:37.311000Z', '2026-04-24T15:56:42.382000Z',
       '2026-04-24T15:57:47.451000Z', '2026-04-24T15:58:52.519000Z',
       '2026-04-30T08:03:35.218032Z', 74424320, 18812928, 74428416,
       18849792, 77176832, 18866176, '2026-05-21T16:31:52.731000Z',
       '2026-05-21T22:26:43.334240Z', '2026-05-21T22:27:00.500000Z',
       '2026-07-12T01:54:48.000000Z', 77271040,
       '2048-04-27T00:51:47.000000Z', 73965568, 3944448, 57176064,
       74235904, 18722816, '2026-03-12T14:55:36.000000Z', 74268672,
       18800640], dtype=object)

In [102]:
system_training_df["entity"].unique()

<StringArray>
[                     'Service de transfert intelligent en arrière-plan',
                                              'Carte de performance WMI',
                               'Service de licences de client (ClipSVC)',
                          'Assistant Connexion avec un compte Microsoft',
                                             'Optimisation de livraison',
                                 'Service de déploiement AppX (AppXSVC)',
                     'Programme d’installation pour les modules Windows',
                                                        'Windows Update',
                                                 'Protection logicielle',
                                       'Service Configuration du réseau',
 ...
                                        '\??\C:\Users\Akorbi\ntuser.dat',
                                        '\??\C:\Users\bayrem\ntuser.dat',
                                      '\??\C:\Users\chahbani\ntuser.dat',
 'Service pour utilisateur de plateforme d’appareils connectés_3e257675',
            'Service utilisateur de notifications Push Windows_3e257675',
                                  'Backup Exec Remote Agent for Windows',
             'Service utilisateur de notifications Push Windows_1e0cc7a',
  'Service pour utilisateur de plateforme d’appareils connectés_1e0cc7a',
            'Service utilisateur de notifications Push Windows_7903e430',
 'Service pour utilisateur de plateforme d’appareils connectés_7903e430']
Length: 239, dtype: str

In [103]:
system_training_df["correlation_activity_id"].unique()

<StringArray>
[                                   nan,
 '0D035ABA-A57E-0004-C05A-030D7EA5DC01',
 'CB7945C3-C0EB-0004-CD45-79CBEBC0DC01',
 'F35698DE-C11D-0004-E298-56F31DC1DC01',
 '4792BFE7-CD26-0004-F1BF-924726CDDC01',
 '9007C991-CDA7-0004-9AC9-0790A7CDDC01',
 'DDCCAB47-CE3D-0004-53AB-CCDD3DCEDC01',
 'E08392A1-AD08-4463-BB00-EC07195D8CFF',
 '8F95BC96-4565-46F3-97BE-DFE416397F6A',
 'C5F6A8CC-CF45-45DC-B868-B969F98957A1',
 '9F108CEF-CAF6-4B92-92A3-0E0772DE5200',
 '4543BAA3-E8B0-4A95-ABA3-F0AE1F1CD18E',
 '18867BB2-2E30-4B1B-B644-734FB0A0418B',
 'F1DAB952-E970-0004-5DB9-DAF170E9DC01']
Length: 14, dtype: str

# Application

In [104]:
application_training_records = parse_application(application_evtx_path)

application_training_records[0]

{'timestamp': {'month_sin': np.float64(1.2246467991473532e-16),
  'second_sin': np.float64(0.0),
  'hour_sin': np.float64(0.49999999999999994),
  'minute_cos': np.float64(0.913545457642601),
  'minute_sin': np.float64(-0.40673664307580015),
  'deltatime': Timedelta('0 days 00:00:20.289018'),
  'day_cos': np.float64(-0.9009688679024191),
  'hour_cos': np.float64(-0.8660254037844387),
  'month_cos': np.float64(-1.0),
  'second_cos': np.float64(1.0),
  'day_sin': np.float64(-0.433883739117558)},
 'profile': {'execution_thread_id': None,
  'event_id_frequency': np.float64(0.9653113448962184),
  'correlation_activity_id': None,
  'previous_event_id': 4,
  'event_id': 4,
  'version': None,
  'event_record_id': 2899035},
 'data': {'entity': None,
  'context': 'php[8696] | PHP Warning: PHP Startup: Unable to load dynamic library \'php_pdo_sqlsrv_74_ts_x64.dll\' (tried: c:/wamp/bin/php/php7.4.0/ext/php_pdo_sqlsrv_74_ts_x64.dll (%1 n’est pas une application Win32 valide.), c:/wamp/bin/php/php7.4.0/ext/php_php_pdo_sqlsrv_74_ts_x64.dll.dll (Le module spécifié est introuvable.)) (php  "C:\\wamp\\www\\CARTENET\\library\\App\\Jobs\\Ckeckifsigned.php")'}}

In [105]:
flat_application_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in application_training_records]

flat_application_training_record[0]

{'month_sin': np.float64(1.2246467991473532e-16),
 'second_sin': np.float64(0.0),
 'hour_sin': np.float64(0.49999999999999994),
 'minute_cos': np.float64(0.913545457642601),
 'minute_sin': np.float64(-0.40673664307580015),
 'deltatime': Timedelta('0 days 00:00:20.289018'),
 'day_cos': np.float64(-0.9009688679024191),
 'hour_cos': np.float64(-0.8660254037844387),
 'month_cos': np.float64(-1.0),
 'second_cos': np.float64(1.0),
 'day_sin': np.float64(-0.433883739117558),
 'execution_thread_id': None,
 'event_id_frequency': np.float64(0.9653113448962184),
 'correlation_activity_id': None,
 'previous_event_id': 4,
 'event_id': 4,
 'version': None,
 'event_record_id': 2899035,
 'entity': None,
 'context': 'php[8696] | PHP Warning: PHP Startup: Unable to load dynamic library \'php_pdo_sqlsrv_74_ts_x64.dll\' (tried: c:/wamp/bin/php/php7.4.0/ext/php_pdo_sqlsrv_74_ts_x64.dll (%1 n’est pas une application Win32 valide.), c:/wamp/bin/php/php7.4.0/ext/php_php_pdo_sqlsrv_74_ts_x64.dll.dll (Le module spécifié est introuvable.)) (php  "C:\\wamp\\www\\CARTENET\\library\\App\\Jobs\\Ckeckifsigned.php")'}

In [106]:
application_training_df = pd.DataFrame(flat_application_training_record)

application_training_df.head(10)

,month_sin,second_sin,hour_sin,minute_cos,minute_sin,deltatime,day_cos,hour_cos,month_cos,second_cos,day_sin,execution_thread_id,event_id_frequency,correlation_activity_id,previous_event_id,event_id,version,event_record_id,entity,context
0,1.224647e-16,0.000000,0.5,0.913545,-0.406737,0 days 00:00:20.289018,-0.900969,-0.866025,-1.0,1.000000,-0.433884,NaN,0.965311,None,4,4,NaN,2899035,NaN,php[8696] | PHP Warning: PHP Startup: Unable t...
1,1.224647e-16,0.309017,0.5,0.913545,-0.406737,0 days 00:00:02.662888,-0.900969,-0.866025,-1.0,0.951057,-0.433884,NaN,0.965311,None,4,4,NaN,2899036,NaN,php[8736] | PHP Warning: PHP Startup: Unable t...
2,1.224647e-16,0.309017,0.5,0.913545,-0.406737,0 days 00:00:00.062795,-0.900969,-0.866025,-1.0,0.951057,-0.433884,NaN,0.965311,None,4,4,NaN,2899037,NaN,php[8456] | PHP Warning: PHP Startup: Unable t...
3,1.224647e-16,0.309017,0.5,0.913545,-0.406737,0 days 00:00:00,-0.900969,-0.866025,-1.0,0.951057,-0.433884,NaN,0.965311,None,4,4,NaN,2899038,NaN,php[4500] | PHP Warning: PHP Startup: Unable t...
4,1.224647e-16,0.309017,0.5,0.913545,-0.406737,0 days 00:00:00.015626,-0.900969,-0.866025,-1.0,0.951057,-0.433884,NaN,0.965311,None,4,4,NaN,2899039,NaN,php[3664] | PHP Warning: PHP Startup: Unable t...
5,1.224647e-16,0.000000,0.5,0.978148,-0.207912,0 days 00:01:57.258522,-0.900969,-0.866025,-1.0,1.000000,-0.433884,NaN,0.965311,None,4,4,NaN,2899040,NaN,php[1176] | PHP Warning: PHP Startup: Unable t...
6,1.224647e-16,0.309017,0.5,0.978148,-0.207912,0 days 00:00:02.284295,-0.900969,-0.866025,-1.0,0.951057,-0.433884,NaN,0.965311,None,4,4,NaN,2899041,NaN,php[3704] | PHP Warning: PHP Startup: Unable t...
7,1.224647e-16,0.309017,0.5,0.978148,-0.207912,0 days 00:00:00,-0.900969,-0.866025,-1.0,0.951057,-0.433884,NaN,0.965311,None,4,4,NaN,2899042,NaN,php[3664] | PHP Warning: PHP Startup: Unable t...
8,1.224647e-16,0.309017,0.5,0.978148,-0.207912,0 days 00:00:00.015627,-0.900969,-0.866025,-1.0,0.951057,-0.433884,NaN,0.965311,None,4,4,NaN,2899043,NaN,php[8788] | PHP Warning: PHP Startup: Unable t...
9,1.224647e-16,0.309017,0.5,0.978148,-0.207912,0 days 00:00:00.015624,-0.900969,-0.866025,-1.0,0.951057,-0.433884,NaN,0.965311,None,4,4,NaN,2899044,NaN,php[7804] | PHP Warning: PHP Startup: Unable t...

In [107]:
application_encoding_types = [
    "None",
    "None",
    "None",
    "None",
    "None",
    "Convert to int",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Presence encoding",
    "None",
    "None",
    "None",
    "None",
    "One-hot encoding",
    "Embedding encoding"
]

In [108]:
application_training_summary = pd.DataFrame({
    "column": application_training_df.columns,
    "dtype": application_training_df.dtypes.astype(str),
    "nunique": application_training_df.nunique(dropna=True),
    "nulls": application_training_df.isna().sum(),
    "encoding": application_encoding_types
}).reset_index(drop=True)

application_training_summary.to_csv(output_path / "parsed_application_profile.csv")

application_training_summary

,column,dtype,nunique,nulls,encoding
0,month_sin,float64,1,0,None
1,second_sin,float64,54,0,None
2,hour_sin,float64,21,0,None
3,minute_cos,float64,51,0,None
4,minute_sin,float64,51,0,None
5,deltatime,timedelta64[us],9808,0,Convert to int
6,day_cos,float64,6,0,None
7,hour_cos,float64,22,0,None
8,month_cos,float64,1,0,None
9,second_cos,float64,53,0,None
10,day_sin,float64,6,0,None
11,execution_thread_id,float64,1,20551,None
12,event_id_frequency,float64,8,0,None
13,correlation_activity_id,object,0,21102,Presence encoding
14,previous_event_id,int64,10,0,None
15,event_id,int64,10,0,None
16,version,float64,1,20551,None
17,event_record_id,int64,21102,0,None
18,entity,str,3,21057,One-hot encoding
19,context,str,6884,15,Embedding encoding

In [109]:
application_training_df['entity'].unique()

<StringArray>
[                                                          nan,
 '86 3b a2 db 28 07 24 23 98 c4 c9 49 00 04 e3 ac 6a 43 69 38',
 '36 a0 aa 09 0f e7 1c 4d 1b 51 87 5f 1c 5a 21 d5 60 c5 93 b5',
 '11 78 48 a9 83 4d 40 17 06 34 11 55 68 fb ad 55 1b a2 0c bf']
Length: 4, dtype: str

# Security

In [110]:
security_training_records = parse_security(security_evtx_path)

security_training_records[0]

{'timestamp': {'month_sin': np.float64(1.2246467991473532e-16),
  'second_sin': np.float64(0.6691306063588582),
  'hour_sin': np.float64(0.0),
  'minute_cos': np.float64(2.83276944882399e-16),
  'minute_sin': np.float64(1.0),
  'deltatime': Timedelta('0 days 00:00:01.096741'),
  'day_cos': np.float64(-0.22252093395631434),
  'hour_cos': np.float64(1.0),
  'month_cos': np.float64(-1.0),
  'second_cos': np.float64(0.7431448254773942),
  'day_sin': np.float64(0.9749279121818236)},
 'profile': {'execution_thread_id': 5960,
  'event_id_frequency': np.float64(0.20136019830928623),
  'correlation_activity_id': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01',
  'previous_event_id': 4624,
  'event_id': 4624,
  'version': 2,
  'event_record_id': 34978816},
 'data': {'value': None,
  'status': None,
  'permission': 'Negotiate',
  'process_name': 'C:\\Windows\\System32\\svchost.exe',
  'entity': 'S-1-5-21-3333335972-2113272682-612058519-500',
  'process_id': None,
  'logon_id': '0x3e7',
  'ip': '-',
  'actor': 'S-1-5-18',
  'context': 4}}

In [111]:
flat_security_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in security_training_records]

flat_security_training_record[0]

{'month_sin': np.float64(1.2246467991473532e-16),
 'second_sin': np.float64(0.6691306063588582),
 'hour_sin': np.float64(0.0),
 'minute_cos': np.float64(2.83276944882399e-16),
 'minute_sin': np.float64(1.0),
 'deltatime': Timedelta('0 days 00:00:01.096741'),
 'day_cos': np.float64(-0.22252093395631434),
 'hour_cos': np.float64(1.0),
 'month_cos': np.float64(-1.0),
 'second_cos': np.float64(0.7431448254773942),
 'day_sin': np.float64(0.9749279121818236),
 'execution_thread_id': 5960,
 'event_id_frequency': np.float64(0.20136019830928623),
 'correlation_activity_id': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01',
 'previous_event_id': 4624,
 'event_id': 4624,
 'version': 2,
 'event_record_id': 34978816,
 'value': None,
 'status': None,
 'permission': 'Negotiate',
 'process_name': 'C:\\Windows\\System32\\svchost.exe',
 'entity': 'S-1-5-21-3333335972-2113272682-612058519-500',
 'process_id': None,
 'logon_id': '0x3e7',
 'ip': '-',
 'actor': 'S-1-5-18',
 'context': 4}

In [112]:
security_training_df = pd.DataFrame(flat_security_training_record)

security_training_df.head(10)

,month_sin,second_sin,hour_sin,minute_cos,minute_sin,deltatime,day_cos,hour_cos,month_cos,second_cos,...,value,status,permission,process_name,entity,process_id,logon_id,ip,actor,context
0,1.224647e-16,0.669131,0.0,2.832769e-16,1.000000,0 days 00:00:01.096741,-0.222521,1.0,-1.0,0.743145,...,None,NaN,Negotiate,C:\Windows\System32\svchost.exe,S-1-5-21-3333335972-2113272682-612058519-500,None,0x3e7,-,S-1-5-18,4
1,1.224647e-16,0.669131,0.0,2.832769e-16,1.000000,0 days 00:00:00.000008,-0.222521,1.0,-1.0,0.743145,...,None,NaN,SeSecurityPrivilege\r\n\t\t\tSeTakeOwnershipPr...,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,0x77061c91,NaN,NaN,None
2,1.224647e-16,0.743145,0.0,2.832769e-16,1.000000,0 days 00:00:00.671212,-0.222521,1.0,-1.0,0.669131,...,None,NaN,NaN,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,0x77061c91,NaN,NaN,4
3,1.224647e-16,-0.500000,0.0,2.832769e-16,1.000000,0 days 00:00:46.664296,-0.222521,1.0,-1.0,0.866025,...,None,NaN,NaN,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,0x770579fb,NaN,NaN,4
4,1.224647e-16,0.000000,0.0,-1.045285e-01,0.994522,0 days 00:00:05.480553,-0.222521,1.0,-1.0,1.000000,...,None,0x0,NaN,NaN,Administrateur,None,NaN,NaN,NaN,None
5,1.224647e-16,0.000000,0.0,-1.045285e-01,0.994522,0 days 00:00:00.000708,-0.222521,1.0,-1.0,1.000000,...,None,NaN,NaN,C:\Windows\System32\svchost.exe,Administrateur,None,0x3e7,-,S-1-5-18,localhost
6,1.224647e-16,0.000000,0.0,-1.045285e-01,0.994522,0 days 00:00:00.000026,-0.222521,1.0,-1.0,1.000000,...,None,NaN,Negotiate,C:\Windows\System32\svchost.exe,S-1-5-21-3333335972-2113272682-612058519-500,None,0x3e7,-,S-1-5-18,4
7,1.224647e-16,0.000000,0.0,-1.045285e-01,0.994522,0 days 00:00:00.000008,-0.222521,1.0,-1.0,1.000000,...,None,NaN,SeSecurityPrivilege\r\n\t\t\tSeTakeOwnershipPr...,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,0x77067629,NaN,NaN,None
8,1.224647e-16,0.207912,0.0,-1.045285e-01,0.994522,0 days 00:00:02.147107,-0.222521,1.0,-1.0,0.978148,...,None,0x0,NaN,NaN,Administrateur,None,NaN,NaN,NaN,None
9,1.224647e-16,0.207912,0.0,-1.045285e-01,0.994522,0 days 00:00:00.001451,-0.222521,1.0,-1.0,0.978148,...,None,0x0,NaN,NaN,Administrateur,None,NaN,NaN,NaN,None

In [113]:
security_encoding_types = [
    "None",
    "None",
    "None",
    "None",
    "None",
    "Convert to int",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Presence encoding",
    "None",
    "None",
    "None",
    "None",
    "Label encoding",
    "Label encoding",
    "Label encoding",
    "One-hot encoding",
    "XML presence encoding",
    "IP address encoding",
    "One-hot encoding",
    "Hex to int encoding",
    "Hex to int encoding",
    "Label encoding"
]

In [114]:
security_training_summary = pd.DataFrame({
    "column": security_training_df.columns,
    "dtype": security_training_df.dtypes.astype(str),
    "nunique": security_training_df.nunique(dropna=True),
    "nulls": security_training_df.isna().sum(),
    "encoding": security_encoding_types
}).reset_index(drop=True)

security_training_summary.to_csv(output_path / "parsed_security_profile.csv")

security_training_summary

,column,dtype,nunique,nulls,encoding
0,month_sin,float64,1,0,None
1,second_sin,float64,53,0,None
2,hour_sin,float64,8,0,None
3,minute_cos,float64,51,0,None
4,minute_sin,float64,52,0,None
5,deltatime,timedelta64[us],8450,0,Convert to int
6,day_cos,float64,1,0,None
7,hour_cos,float64,10,0,None
8,month_cos,float64,1,0,None
9,second_cos,float64,51,0,None
10,day_sin,float64,1,0,None
11,execution_thread_id,int64,171,0,None
12,event_id_frequency,float64,12,0,None
13,correlation_activity_id,str,6186,6197,Presence encoding
14,previous_event_id,int64,17,0,None
15,event_id,int64,17,0,None
16,version,int64,3,0,None
17,event_record_id,int64,31466,0,None
18,value,object,42,31371,Label encoding
19,status,str,1,25281,Label encoding
20,permission,str,9,18784,Label encoding
21,process_name,str,5,18941,One-hot encoding
22,entity,str,44,3,XML presence encoding
23,process_id,object,63,31256,IP address encoding
24,logon_id,str,6204,6200,One-hot encoding
25,ip,str,3,18941,Hex to int encoding
26,actor,str,6,18717,Hex to int encoding
27,context,object,12,12692,Label encoding

In [117]:
security_training_df['entity'].unique()

<StringArray>
[                               'S-1-5-21-3333335972-2113272682-612058519-500',
                                                              'Administrateur',
                                                                    'S-1-5-18',
                            '\Microsoft\Windows\WindowsUpdate\Scheduled Start',
                                                                'S-1-5-32-544',
                                                                'S-1-5-32-551',
                '\Microsoft\Windows\SoftwareProtectionPlatform\SvcRestartTask',
           '\User_Feed_Synchronization-{2BA688E8-D52A-4E7D-AFD8-2070D64559BD}',
                                            'root\CIMV2\security\microsofttpm',
                                            'root\cimv2\Security\MicrosoftTpm',
                                            'root\CIMV2\Security\MicrosoftTPM',
                                '\Microsoft\Windows\Device Information\Device',
 '\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser',
                         '\Microsoft\Windows\UpdateOrchestrator\Schedule Scan',
                     '\Microsoft\Windows\UpdateOrchestrator\AC Power Download',
                                                                     'ESANTE$',
                      'WindowsLive:(token):name=02ymtxsadbquxmim;serviceuri=*',
                       'WindowsLive:(cert):name=02ymtxsadbquxmim;serviceuri=*',
                                    'WindowsLive:target=virtualapp/didlogical',
                      'WindowsLive:(token):name=02fqyrlzesevgine;serviceuri=*',
                       'WindowsLive:(cert):name=02fqyrlzesevgine;serviceuri=*',
                                      'MicrosoftAccount:user=02fqyrlzesevgine',
                      'WindowsLive:(token):name=02ethngozfmszzgm;serviceuri=*',
                       'WindowsLive:(cert):name=02ethngozfmszzgm;serviceuri=*',
                                      'MicrosoftAccount:user=02ethngozfmszzgm',
                                'S-1-5-21-3073298170-276159943-2983424533-500',
                                                                      'UMFD-3',
                                                                'S-1-5-96-0-3',
                                                                       'DWM-3',
                                                                'S-1-5-90-0-3',
                                                                           nan,
                                                     'CaptureService_7903e430',
                                                            'cbdhsvc_7903e430',
                                                         'CDPUserSvc_7903e430',
                                                   'ConsentUxUserSvc_7903e430',
                                                'DevicePickerUserSvc_7903e430',
                                                 'DevicesFlowUserSvc_7903e430',
                                             'PimIndexMaintenanceSvc_7903e430',
                                               'PrintWorkflowUserSvc_7903e430',
                                                        'UnistoreSvc_7903e430',
                                                        'UserDataSvc_7903e430',
                                                     'WpnUserService_7903e430',
                     'Microsoft Connected Devices Platform device certificate',
                                          '\CreateExplorerShellUnelevatedTask',
                                                              'ServerManager*']
Length: 45, dtype: str

In [115]:
security_training_df['context'].unique()

array([4, None, 'localhost', 5, 3, 'Object Access', 'esante$', '%%8100',
       2, 10, '%%2458', '%%2480', '%%2464'], dtype=object)

In [116]:
security_training_df['value'].unique()

array([None,
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>Microsoft Corporation.</Source>\r\n    <Author>Microsoft Corporation.</Author>\r\n    <Description>Cette tâche permet de démarrer le service Windows Update lorsque des opérations planifiées, comme des analyses, doivent être effectuées.</Description>\r\n    <URI>\\Microsoft\\Windows\\WindowsUpdate\\Scheduled Start</URI>\r\n    <SecurityDescriptor>D:(A;;FA;;;SY)(A;;FRFX;;;LS)(A;;FA;;;BA)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <TimeTrigger>\r\n      <StartBoundary>2026-06-17T17:15:29Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <RandomDelay>PT1M</RandomDelay>\r\n    </TimeTrigger>\r\n    <SessionStateChangeTrigger>\r\n      <Enabled>false</Enabled>\r\n      <StateChange>ConsoleDisconnect</StateChange>\r\n    </SessionStateChangeTrigger>\r\n    <SessionStateChangeTrigger>\r\n      <Enabled>false</Enabled>\r\n      <StateChange>RemoteDisconnect</StateChange>\r\n    </SessionStateChangeTrigger>\r\n    <WnfStateChangeTrigger>\r\n      <Enabled>false</Enabled>\r\n      <StateName>7508BCA3380C960C</StateName>\r\n      <Data>01</Data>\r\n      <DataOffset>0</DataOffset>\r\n    </WnfStateChangeTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="LocalSystem">\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n      <UserId>NT AUTHORITY\\SYSTEM</UserId>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>true</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <Duration>PT10M</Duration>\r\n      <WaitTimeout>PT1H</WaitTimeout>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>false</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>false</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n  </Settings>\r\n  <Actions Context="LocalSystem">\r\n    <Exec>\r\n      <Command>C:\\WINDOWS\\system32\\sc.exe</Command>\r\n      <Arguments>start wuauserv</Arguments>\r\n    </Exec>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T01:12:55Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T01:42:55Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.3" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Author>ESANTE\\Administrateur</Author>\r\n    <Description>Met à jour les flux système obsolètes.</Description>\r\n    <URI>\\User_Feed_Synchronization-{2BA688E8-D52A-4E7D-AFD8-2070D64559BD}</URI>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2026-06-17T08:22:50Z</StartBoundary>\r\n      <EndBoundary>2036-06-17T08:22:50Z</EndBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="Author">\r\n      <UserId>S-1-5-21-3333335972-2113272682-612058519-500</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n      <LogonType>InteractiveToken</LogonType>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>true</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <Duration>PT10M</Duration>\r\n      <WaitTimeout>PT1H</WaitTimeout>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n  </Settings>\r\n  <Actions Context="Author">\r\n    <Exec>\r\n      <Command>C:\\WINDOWS\\system32\\msfeedssync.exe</Command>\r\n      <Arguments>sync</Arguments>\r\n    </Exec>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T02:12:55Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Version>1.0</Version>\r\n    <URI>\\Microsoft\\Windows\\Device Information\\Device</URI>\r\n    <SecurityDescriptor>D:(A;;GA;;;BA)(A;;GA;;;SY)(A;;FRFX;;;LS)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <TimeTrigger>\r\n      <Repetition>\r\n        <Interval>P1D</Interval>\r\n        <StopAtDurationEnd>false</StopAtDurationEnd>\r\n      </Repetition>\r\n      <StartBoundary>2008-09-01T03:00:00</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <RandomDelay>PT2H</RandomDelay>\r\n    </TimeTrigger>\r\n    <WnfStateChangeTrigger id="WNF_DEP_OOBE_COMPLETE">\r\n      <Enabled>false</Enabled>\r\n      <StateName>750CBCA3290B9641</StateName>\r\n      <Data>01</Data>\r\n      <DataOffset>0</DataOffset>\r\n    </WnfStateChangeTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="LocalSystem">\r\n      <UserId>S-1-5-18</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>true</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>false</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>P4D</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n  </Settings>\r\n  <Actions Context="LocalSystem">\r\n    <Exec>\r\n      <Command>%windir%\\system32\\devicecensus.exe</Command>\r\n    </Exec>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T02:41:58Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',
       '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Source>$(@%systemroot%\\system32\\sppc.dll,-200)</Source>\r\n    <Author>$(@%systemroot%\\system32\\sppc.dll,-200)</Author>\r\n    <Version>1.0</Version>\r\n    <Description>$(@%systemroot%\\system32\\sppc.dll,-201)</Description>\r\n    <URI>\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask</URI>\r\n    <SecurityDescriptor>D:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-80-123231216-2592883651-3715271367-3753151631-4175906628)(A;;FR;;;S-1-5-87-2912274048-3994893941-1669128114-1310430903-1263774323)</SecurityDescriptor>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <CalendarTrigger>\r\n      <StartBoundary>2126-05-24T02:43:17Z</StartBoundary>\r\n      <Enabled>true</Enabled>\r\n      <ScheduleByDay>\r\n        <DaysInterval>1</DaysInterval>\r\n      </ScheduleByDay>\r\n    </CalendarTrigger>\r\n  </Triggers>\r\n  <Principals>\r\n    <Principal id="NetworkService">\r\n      <UserId>S-1-5-20</UserId>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>false</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>true</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\r\n    <Priority>7</Priority>\r\n    <RestartOnFailure>\r\n      <Interval>PT1M</Interval>\r\n      <Count>3</Count>\r\n    </RestartOnFailure>\r\n  </Settings>\r\n  <Actions Context="NetworkService">\r\n    <ComHandler>\r\n      <ClassId>{B1AEBB5D-EAD9-4476-B375-9C3ED9F32AFC}</ClassId>\r\n      <Data><![CDATA[timer]]></Data>\r\n    </ComHandler>\r\n  </Actions>\r\n</Task>',