# Training application model

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path
from anomaly_detection.parser.data_parsers import parse_application
from anomaly_detection.transformers import application_transformer

c:\Users\hp\AppData\Local\pypoetry\Cache\virtualenvs\anomaly-detection-mxkT3iGB-py3.12\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Path to the data
project_folder = Path.cwd().parent

output_path = project_folder / "data/training"

application_evtx_path = project_folder / "data/raw/93_applog.evtx"

application_evtx_path

WindowsPath('c:/Users/hp/Documents/School/anomaly-detection/data/raw/93_applog.evtx')

# Data preparation

In [3]:
application_training_records = parse_application(application_evtx_path)

application_training_records[0]

{'timestamp': {'day_cos': np.float64(-0.9009688679024191),
  'hour_cos': np.float64(-0.8660254037844387),
  'hour_sin': np.float64(0.49999999999999994),
  'minute_cos': np.float64(0.913545457642601),
  'second_cos': np.float64(1.0),
  'month_sin': np.float64(1.2246467991473532e-16),
  'day_sin': np.float64(-0.433883739117558),
  'month_cos': np.float64(-1.0),
  'minute_sin': np.float64(-0.40673664307580015),
  'second_sin': np.float64(0.0),
  'deltatime': Timedelta('0 days 00:00:20.289018')},
 'profile': {'correlation_activity_id': None,
  'previous_event_id': 4,
  'event_id': 4,
  'version': None,
  'event_id_frequency': np.float64(0.9653113448962184),
  'execution_thread_id': None,
  'event_record_id': 2899035},
 'data': {'context': 'php[8696] | PHP Warning: PHP Startup: Unable to load dynamic library \'php_pdo_sqlsrv_74_ts_x64.dll\' (tried: c:/wamp/bin/php/php7.4.0/ext/php_pdo_sqlsrv_74_ts_x64.dll (%1 n’est pas une application Win32 valide.), c:/wamp/bin/php/php7.4.0/ext/php_php_pdo_sqlsrv_74_ts_x64.dll.dll (Le module spécifié est introuvable.)) (php  "C:\\wamp\\www\\CARTENET\\library\\App\\Jobs\\Ckeckifsigned.php")',
  'entity': None}}

In [4]:
flat_application_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in application_training_records]

flat_application_training_record[0]

{'day_cos': np.float64(-0.9009688679024191),
 'hour_cos': np.float64(-0.8660254037844387),
 'hour_sin': np.float64(0.49999999999999994),
 'minute_cos': np.float64(0.913545457642601),
 'second_cos': np.float64(1.0),
 'month_sin': np.float64(1.2246467991473532e-16),
 'day_sin': np.float64(-0.433883739117558),
 'month_cos': np.float64(-1.0),
 'minute_sin': np.float64(-0.40673664307580015),
 'second_sin': np.float64(0.0),
 'deltatime': Timedelta('0 days 00:00:20.289018'),
 'correlation_activity_id': None,
 'previous_event_id': 4,
 'event_id': 4,
 'version': None,
 'event_id_frequency': np.float64(0.9653113448962184),
 'execution_thread_id': None,
 'event_record_id': 2899035,
 'context': 'php[8696] | PHP Warning: PHP Startup: Unable to load dynamic library \'php_pdo_sqlsrv_74_ts_x64.dll\' (tried: c:/wamp/bin/php/php7.4.0/ext/php_pdo_sqlsrv_74_ts_x64.dll (%1 n’est pas une application Win32 valide.), c:/wamp/bin/php/php7.4.0/ext/php_php_pdo_sqlsrv_74_ts_x64.dll.dll (Le module spécifié est introuvable.)) (php  "C:\\wamp\\www\\CARTENET\\library\\App\\Jobs\\Ckeckifsigned.php")',
 'entity': None}

In [5]:
application_training_df = pd.DataFrame(flat_application_training_record)

application_training_df.head(10)

,day_cos,hour_cos,hour_sin,minute_cos,second_cos,month_sin,day_sin,month_cos,minute_sin,second_sin,deltatime,correlation_activity_id,previous_event_id,event_id,version,event_id_frequency,execution_thread_id,event_record_id,context,entity
0,-0.900969,-0.866025,0.5,0.913545,1.000000,1.224647e-16,-0.433884,-1.0,-0.406737,0.000000,0 days 00:00:20.289018,None,4,4,NaN,0.965311,NaN,2899035,php[8696] | PHP Warning: PHP Startup: Unable t...,NaN
1,-0.900969,-0.866025,0.5,0.913545,0.951057,1.224647e-16,-0.433884,-1.0,-0.406737,0.309017,0 days 00:00:02.662888,None,4,4,NaN,0.965311,NaN,2899036,php[8736] | PHP Warning: PHP Startup: Unable t...,NaN
2,-0.900969,-0.866025,0.5,0.913545,0.951057,1.224647e-16,-0.433884,-1.0,-0.406737,0.309017,0 days 00:00:00.062795,None,4,4,NaN,0.965311,NaN,2899037,php[8456] | PHP Warning: PHP Startup: Unable t...,NaN
3,-0.900969,-0.866025,0.5,0.913545,0.951057,1.224647e-16,-0.433884,-1.0,-0.406737,0.309017,0 days 00:00:00,None,4,4,NaN,0.965311,NaN,2899038,php[4500] | PHP Warning: PHP Startup: Unable t...,NaN
4,-0.900969,-0.866025,0.5,0.913545,0.951057,1.224647e-16,-0.433884,-1.0,-0.406737,0.309017,0 days 00:00:00.015626,None,4,4,NaN,0.965311,NaN,2899039,php[3664] | PHP Warning: PHP Startup: Unable t...,NaN
5,-0.900969,-0.866025,0.5,0.978148,1.000000,1.224647e-16,-0.433884,-1.0,-0.207912,0.000000,0 days 00:01:57.258522,None,4,4,NaN,0.965311,NaN,2899040,php[1176] | PHP Warning: PHP Startup: Unable t...,NaN
6,-0.900969,-0.866025,0.5,0.978148,0.951057,1.224647e-16,-0.433884,-1.0,-0.207912,0.309017,0 days 00:00:02.284295,None,4,4,NaN,0.965311,NaN,2899041,php[3704] | PHP Warning: PHP Startup: Unable t...,NaN
7,-0.900969,-0.866025,0.5,0.978148,0.951057,1.224647e-16,-0.433884,-1.0,-0.207912,0.309017,0 days 00:00:00,None,4,4,NaN,0.965311,NaN,2899042,php[3664] | PHP Warning: PHP Startup: Unable t...,NaN
8,-0.900969,-0.866025,0.5,0.978148,0.951057,1.224647e-16,-0.433884,-1.0,-0.207912,0.309017,0 days 00:00:00.015627,None,4,4,NaN,0.965311,NaN,2899043,php[8788] | PHP Warning: PHP Startup: Unable t...,NaN
9,-0.900969,-0.866025,0.5,0.978148,0.951057,1.224647e-16,-0.433884,-1.0,-0.207912,0.309017,0 days 00:00:00.015624,None,4,4,NaN,0.965311,NaN,2899044,php[7804] | PHP Warning: PHP Startup: Unable t...,NaN

In [6]:
X_application = application_transformer.fit_transform(application_training_df)

X_application[0]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5648.34it/s]
Batches: 100%|██████████| 83/83 [19:15<00:00, 13.92s/it]

KeyboardInterrupt:

In [ ]:
X_application = pd.DataFrame(
    application_transformer.fit_transform(application_training_df),
    columns=application_transformer.get_feature_names_out(),
    index=application_training_df.index,
)

X_application.head()

In [ ]:
X_application = np.nan_to_num(X_application)

X_application[0]

array([ 2.02890180e+01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  1.56747234e+00,  2.37716436e+00,
        1.47615921e+00,  7.97773409e+00,  1.81370124e-01,  3.48278105e-01,
        1.05106127e+00,  1.62763739e+00, -3.57082629e+00,  2.71447730e+00,
       -5.26812494e-01,  6.54640734e-01,  9.16371047e-01, -1.31320367e-02,
        7.04085752e-02,  1.46167600e+00,  2.93965578e-01,  1.83607638e+00,
       -1.18680261e-01,  1.62219965e+00,  1.56490016e+00,  3.62568527e-01,
       -6.33005053e-02, -2.20411811e-02, -8.20095837e-01, -4.67328370e-01,
        1.43247938e+00, -1.06439646e-02, -6.59148455e-01,  1.11284506e+00,
       -5.09854853e-01, -7.43423283e-01, -4.33883739e-01, -8.66025404e-01,
       -9.00968868e-01,  5.00000000e-01,  1.22464680e-16, -1.00000000e+00,
        1.00000000e+00,  9.13545458e-01,  0.00000000e+00, -4.06736643e-01,
        9.65311345e-01,  0.00000000e+00,  4.00000000e+00,  4.00000000e+00,
        2.89903500e+06,  0.00000000e+00])

In [ ]:
pd.DataFrame(X_application).describe().T

,count,mean,std,min,25%,50%,75%,max
0,21102.0,2.028902e+01,3.876192e+01,0.000000e+00,0.000000e+00,6.249800e-02,6.280957e+00,1.208190e+02
1,21102.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,21102.0,7.108331e-04,2.665261e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
3,21102.0,7.108331e-04,2.665261e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
4,21102.0,7.108331e-04,2.665261e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
5,21102.0,9.978675e-01,4.613082e-02,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
6,21102.0,-3.327870e-08,1.257596e+01,-7.537086e+01,2.014989e+00,2.349626e+00,2.613757e+00,3.455767e+00
7,21102.0,1.120660e-07,7.700811e+00,-4.808372e+01,-8.481150e-01,-2.494488e-01,6.748063e-01,4.859853e+01
8,21102.0,-4.774577e-08,5.322595e+00,-5.857075e+01,-5.574267e-01,3.304856e-01,1.245421e+00,1.863764e+01
9,21102.0,-1.616561e-07,5.022324e+00,-1.068186e+01,-2.487061e+00,-1.769500e+00,2.337928e+00,1.648698e+01
10,21102.0,-7.131794e-08,4.335589e+00,-5.871838e+01,-4.121865e-01,9.037787e-02,6.309592e-01,3.996205e+01
11,21102.0,3.410661e-08,3.842967e+00,-2.240393e+01,-1.495043e-01,4.581345e-01,9.375862e-01,6.877492e+01
12,21102.0,9.029990e-08,3.346281e+00,-1.528393e+01,-2.306340e+00,-1.646831e+00,2.731038e+00,1.840075e+01
13,21102.0,-5.665089e-08,2.478604e+00,-2.748663e+01,-1.165541e+00,-2.943079e-02,1.151254e+00,3.350589e+01
14,21102.0,3.497621e-08,2.240704e+00,-9.650898e+00,-1.481247e+00,1.364894e-01,1.617091e+00,8.367418e+00
15,21102.0,-1.080235e-07,2.082694e+00,-2.119960e+01,-1.173678e+00,-1.394956e-01,1.090991e+00,1.636094e+01
16,21102.0,-5.659143e-09,1.883410e+00,-7.945293e+00,-1.218584e+00,-4.617789e-03,1.369206e+00,9.206509e+00
17,21102.0,9.099254e-08,1.795458e+00,-1.369337e+01,-1.056527e+00,6.893430e-02,1.131512e+00,9.855528e+00
18,21102.0,1.030907e-07,1.683319e+00,-6.480378e+00,-9.184971e-01,-4.160004e-02,8.480555e-01,1.099384e+01
19,21102.0,-6.037578e-08,1.598747e+00,-8.510406e+00,-1.055359e+00,-1.295984e-01,8.466189e-01,6.398301e+00
20,21102.0,-3.357579e-08,1.558212e+00,-1.121123e+01,-8.051131e-01,-5.932902e-03,8.785120e-01,8.844160e+00
21,21102.0,1.520531e-08,1.536499e+00,-1.148659e+01,-7.399963e-01,1.084386e-01,9.052135e-01,8.022906e+00
22,21102.0,-4.938077e-08,1.441559e+00,-8.375112e+00,-7.361974e-01,7.454970e-02,8.073905e-01,7.492737e+00
23,21102.0,-1.981808e-08,1.335544e+00,-9.959864e+00,-6.368870e-01,6.128802e-02,6.946446e-01,1.003333e+01
24,21102.0,-4.387125e-08,1.318848e+00,-7.435989e+00,-6.968119e-01,-1.164536e-02,7.124809e-01,9.703420e+00
25,21102.0,-7.515624e-08,1.299832e+00,-6.034058e+00,-7.468181e-01,9.417250e-02,8.646791e-01,1.062005e+01
26,21102.0,-2.459202e-08,1.244613e+00,-7.127985e+00,-6.296209e-01,1.283583e-01,7.576002e-01,8.091216e+00
27,21102.0,-2.815898e-08,1.189217e+00,-1.142791e+01,-4.565171e-01,9.260227e-02,5.956443e-01,6.485000e+00
28,21102.0,-3.489857e-08,1.151218e+00,-5.180504e+00,-7.109444e-01,-5.772241e-02,6.947825e-01,7.664492e+00
29,21102.0,-3.138254e-08,1.132008e+00,-5.261077e+00,-6.478220e-01,-8.595743e-02,5.412360e-01,1.433067e+01
30,21102.0,-6.148157e-09,1.089036e+00,-5.938855e+00,-5.812991e-01,7.095365e-02,6.175696e-01,1.445113e+01
31,21102.0,1.552275e-08,1.065138e+00,-8.563566e+00,-5.216900e-01,8.815196e-02,6.266989e-01,5.899813e+00
32,21102.0,4.322179e-08,1.038069e+00,-4.813766e+00,-5.668732e-01,2.086776e-03,5.476134e-01,7.080024e+00
33,21102.0,2.410136e-08,9.942963e-01,-6.593240e+00,-5.698314e-01,-3.770391e-02,6.040787e-01,8.286779e+00
34,21102.0,-7.021320e-08,9.644725e-01,-6.978857e+00,-4.865510e-01,-1.464200e-02,4.720422e-01,7.173987e+00
35,21102.0,-1.440197e-08,9.239735e-01,-9.500490e+00,-4.660370e-01,2.383523e-02,4.659390e-01,4.707715e+00
36,21102.0,4.254342e-08,9.105157e-01,-2.052135e+01,-4.362153e-01,-8.404463e-02,3.723137e-01,7.144289e+00
37,21102.0,1.017244e-07,8.302176e-01,-8.773238e+00,-3.954547e-01,1.607739e-03,3.994695e-01,5.498071e+00
38,21102.0,-1.559537e-01,7.135880e-01,-9.749279e-01,-7.818315e-01,-4.338837e-01,7.818315e-01,9.749279e-01
39,21102.0,2.662175e-03,7.056673e-01,-1.000000e+00,-7.071068e-01,6.123234e-17,7.071068e-01,1.000000e+00
40,21102.0,3.003281e-01,6.134457e-01,-9.009689e-01,-2.225209e-01,6.234898e-01,6.234898e-01,1.000000e+00
41,21102.0,-1.744834e-04,7.085718e-01,-1.000000e+00,-7.071068e-01,0.000000e+00,7.071068e-01,1.000000e+00
42,21102.0,1.224647e-16,2.465249e-32,1.224647e-16,1.224647e-16,1.224647e-16,1.224647e-16,1.224647e-16
43,21102.0,-1.000000e+00,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00
44,21102.0,9.011307e-01,3.273307e-01,-1.000000e+00,9.781476e-01,9.781476e-01,9.781476e-01,1.000000e+00
45,21102.0,6.435743e-03,7.094664e-01,-1.000000e+00,-6.691306e-01,2.832769e-16,6.691306e-01,1.000000e+00
46,21102.0,1.990825e-01,2.029564e-01,-1.000000e+00,1.045285e-01,2.079117e-01,2.079117e-01,1.000000e+00
47,21102.0,8.399174e-04,7.047430e-01,-1.000000e+00,-7.431448e-01,0.000000e+00,7.431448e-01,1.000000e+00
48,21102.0,9.321398e-01,1.749929e-01,4.738887e-05,9.653113e-01,9.653113e-01,9.653113e-01,9.653113e-01
49,21102.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50,21102.0,4.160112e+02,2.516403e+03,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,1.639400e+04
51,21102.0,4.160112e+02,2.516403e+03,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,1.639400e+04
52,21102.0,2.909586e+06,6.091767e+03,2.899035e+06,2.904310e+06,2.909586e+06,2.914861e+06,2.920136e+06
53,21102.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

# Modeling

In [ ]:
from sklearn.ensemble import IsolationForest

application_model = IsolationForest(
    n_estimators=512,
    contamination=0.0001,
    max_features=0.8,
    max_samples=4096,
    n_jobs=-1,
)

application_model.fit(X_application)

IsolationForest(contamination=0.0001, max_features=0.8, max_samples=4096,
                n_estimators=512, n_jobs=-1)

In [ ]:
scores = application_model.decision_function(X_application)
predictions = application_model.predict(X_application)

In [ ]:
results = application_training_df.copy()

results["anomaly_score"] = scores
results["prediction"] = predictions

results.head()

,day_sin,hour_cos,day_cos,deltatime,hour_sin,month_sin,month_cos,second_cos,minute_cos,second_sin,...,event_id_frequency,execution_thread_id,event_id,previous_event_id,event_record_id,version,entity,context,anomaly_score,prediction
0,-0.433884,-0.866025,-0.900969,0 days 00:00:20.289018,0.5,1.224647e-16,-1.0,1.000000,0.913545,0.000000,...,0.965311,NaN,4,4,2899035,NaN,NaN,php[8696] | PHP Warning: PHP Startup: Unable t...,0.309483,1
1,-0.433884,-0.866025,-0.900969,0 days 00:00:02.662888,0.5,1.224647e-16,-1.0,0.951057,0.913545,0.309017,...,0.965311,NaN,4,4,2899036,NaN,NaN,php[8736] | PHP Warning: PHP Startup: Unable t...,0.317849,1
2,-0.433884,-0.866025,-0.900969,0 days 00:00:00.062795,0.5,1.224647e-16,-1.0,0.951057,0.913545,0.309017,...,0.965311,NaN,4,4,2899037,NaN,NaN,php[8456] | PHP Warning: PHP Startup: Unable t...,0.325374,1
3,-0.433884,-0.866025,-0.900969,0 days 00:00:00,0.5,1.224647e-16,-1.0,0.951057,0.913545,0.309017,...,0.965311,NaN,4,4,2899038,NaN,NaN,php[4500] | PHP Warning: PHP Startup: Unable t...,0.285222,1
4,-0.433884,-0.866025,-0.900969,0 days 00:00:00.015626,0.5,1.224647e-16,-1.0,0.951057,0.913545,0.309017,...,0.965311,NaN,4,4,2899039,NaN,NaN,php[3664] | PHP Warning: PHP Startup: Unable t...,0.314853,1

In [ ]:
results.sort_values("anomaly_score").head(50)

,day_sin,hour_cos,day_cos,deltatime,hour_sin,month_sin,month_cos,second_cos,minute_cos,second_sin,...,event_id_frequency,execution_thread_id,event_id,previous_event_id,event_record_id,version,entity,context,anomaly_score,prediction
12837,0.000000,-9.659258e-01,1.000000,0 days 00:00:00.765621,2.588190e-01,1.224647e-16,-1.0,3.090170e-01,-0.994522,9.510565e-01,...,0.002701,NaN,1001,1001,2911872,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,-0.006385,-1
12836,0.000000,-9.659258e-01,1.000000,0 days 00:00:00.734370,2.588190e-01,1.224647e-16,-1.0,4.067366e-01,-0.994522,9.135455e-01,...,0.002701,NaN,1001,1001,2911871,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,-0.005181,-1
12719,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.078123,5.000000e-01,1.224647e-16,-1.0,-7.431448e-01,0.743145,-6.691306e-01,...,0.002701,NaN,1001,1001,2911754,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,-0.000067,-1
12718,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.062500,5.000000e-01,1.224647e-16,-1.0,-7.431448e-01,0.743145,-6.691306e-01,...,0.002701,NaN,1001,1001,2911753,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.000543,1
12722,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.046880,5.000000e-01,1.224647e-16,-1.0,-7.431448e-01,0.743145,-6.691306e-01,...,0.002701,NaN,1001,1001,2911757,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.000664,1
12717,0.000000,-8.660254e-01,1.000000,0 days 00:00:06.781203,5.000000e-01,1.224647e-16,-1.0,-7.431448e-01,0.743145,-6.691306e-01,...,0.002701,NaN,1001,1000,2911752,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.001247,1
12746,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.046870,5.000000e-01,1.224647e-16,-1.0,7.431448e-01,0.994522,6.691306e-01,...,0.002701,NaN,1001,1001,2911781,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.001748,1
12721,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.046877,5.000000e-01,1.224647e-16,-1.0,-7.431448e-01,0.743145,-6.691306e-01,...,0.002701,NaN,1001,1001,2911756,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.001768,1
12835,0.000000,-9.659258e-01,1.000000,0 days 00:01:07.515323,2.588190e-01,1.224647e-16,-1.0,5.000000e-01,-0.994522,8.660254e-01,...,0.002701,NaN,1001,4,2911870,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.003030,1
12709,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.124997,5.000000e-01,1.224647e-16,-1.0,6.691306e-01,0.743145,7.431448e-01,...,0.002701,NaN,1001,1001,2911744,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.003671,1
12723,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.062494,5.000000e-01,1.224647e-16,-1.0,-7.431448e-01,0.743145,-6.691306e-01,...,0.002701,NaN,1001,1001,2911758,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.004529,1
12745,0.000000,-8.660254e-01,1.000000,0 days 00:00:07.593698,5.000000e-01,1.224647e-16,-1.0,7.431448e-01,0.994522,6.691306e-01,...,0.002701,NaN,1001,1001,2911780,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.005697,1
12747,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.031252,5.000000e-01,1.224647e-16,-1.0,7.431448e-01,0.994522,6.691306e-01,...,0.002701,NaN,1001,1001,2911782,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.005914,1
12712,0.000000,-8.660254e-01,1.000000,0 days 00:00:15.110907,5.000000e-01,1.224647e-16,-1.0,-8.660254e-01,0.743145,5.000000e-01,...,0.002701,NaN,1001,1000,2911747,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.006728,1
12706,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.156254,5.000000e-01,1.224647e-16,-1.0,8.090170e-01,0.743145,5.877853e-01,...,0.002701,NaN,1001,1001,2911741,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.013381,1
394,-0.433884,-9.659258e-01,-0.900969,0 days 00:00:41.407592,-2.588190e-01,1.224647e-16,-1.0,6.691306e-01,0.207912,7.431448e-01,...,0.011989,0.0,16384,16394,2899429,0.0,NaN,2126-05-19T13:13:08Z | RulesEngine,0.035816,1
12720,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.078121,5.000000e-01,1.224647e-16,-1.0,-7.431448e-01,0.743145,-6.691306e-01,...,0.002701,NaN,1001,1001,2911755,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.036741,1
2894,-0.974928,7.071068e-01,-0.222521,0 days 00:00:32.337903,7.071068e-01,1.224647e-16,-1.0,5.000000e-01,-0.866025,-8.660254e-01,...,0.011989,0.0,16384,16394,2901929,0.0,NaN,2126-05-20T03:35:50Z | RulesEngine,0.040086,1
12714,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.015623,5.000000e-01,1.224647e-16,-1.0,-9.135455e-01,0.743145,4.067366e-01,...,0.002701,NaN,1001,4,2911749,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.045461,1
12701,0.000000,-8.660254e-01,1.000000,0 days 00:00:32.425409,5.000000e-01,1.224647e-16,-1.0,8.660254e-01,0.669131,-5.000000e-01,...,0.002701,NaN,1001,1000,2911736,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.045743,1
12705,0.000000,-8.660254e-01,1.000000,0 days 00:00:07.661270,5.000000e-01,1.224647e-16,-1.0,8.090170e-01,0.743145,5.877853e-01,...,0.002701,NaN,1001,1000,2911740,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.047527,1
12708,0.000000,-8.660254e-01,1.000000,0 days 00:00:00.437497,5.000000e-01,1.224647e-16,-1.0,6.691306e-01,0.743145,7.431448e-01,...,0.002701,NaN,1001,4,2911743,NaN,NaN,| 0 | BEX | Non disponible | 0 | httpd.exe | ...,0.051039,1
1959,-0.433884,8.660254e-01,-0.900969,0 days 00:00:56.496319,-5.000000e-01,1.224647e-16,-1.0,-7.431448e-01,0.207912,6.691306e-01,...,0.011989,0.0,16384,16394,2900994,0.0,NaN,2126-05-19T22:13:23Z | RulesEngine,0.054763,1
6908,-0.781831,8.660254e-01,0.623490,0 days 00:00:32.271891,5.000000e-01,1.224647e-16,-1.0,-9.781476e-01,-0.951057,-2.079117e-01,...,0.011989,0.0,16384,16394,2905943,0.0,NaN,2126-05-21T02:33:32Z | RulesEngine,0.055265,1
12726,0.000000,-8.660254e-01,1.000000,0 days 00:00:04.618961,5.000000e-01,1.224647e-16,-1.0,-2.079117e-01,0.743145,-9.781476e-01,...,0.001896,NaN,1000,4,2911761,NaN,NaN,httpd.exe | 2.4.41.0 | 5d4d8438 | php7ts.dll |...,0.055909,1
12509,0.000000,-7.071068e-01,1.000000,0 days 00:00:04.018235,7.071068e-01,1.224647e-16,-1.0,-1.045285e-01,0.743145,-9.945219e-01,...,0.002701,NaN,1001,1000,2911544,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.070546,1
20992,0.974928,-7.071068e-01,-0.222521,0 days 00:00:44.093511,7.071068e-01,1.224647e-16,-1.0,6.691306e-01,0.207912,7.431448e-01,...,0.011989,0.0,16384,16394,2920027,0.0,NaN,2126-05-24T09:13:08Z | RulesEngine,0.070579,1
12392,0.000000,-7.071068e-01,1.000000,0 days 00:00:06.060374,7.071068e-01,1.224647e-16,-1.0,3.090170e-01,-0.978148,-9.510565e-01,...,0.001896,NaN,1000,4,2911427,NaN,NaN,httpd.exe | 2.4.41.0 | 5d4d8438 | php7ts.dll |...,0.071118,1
12727,0.000000,-8.660254e-01,1.000000,0 days 00:00:10.178895,5.000000e-01,1.224647e-16,-1.0,8.090170e-01,0.743145,-5.877853e-01,...,0.002701,NaN,1001,1000,2911762,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.073141,1
12355,0.000000,-7.071068e-01,1.000000,0 days 00:00:16.377808,7.071068e-01,1.224647e-16,-1.0,-4.067366e-01,-0.913545,9.135455e-01,...,0.001896,NaN,1000,4,2911390,NaN,NaN,httpd.exe | 2.4.41.0 | 5d4d8438 | php7ts.dll |...,0.073378,1
12491,0.000000,-7.071068e-01,1.000000,0 days 00:00:05.537428,7.071068e-01,1.224647e-16,-1.0,7.431448e-01,0.669131,-6.691306e-01,...,0.002701,NaN,1001,1000,2911526,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.075358,1
8588,-0.781831,-1.000000e+00,0.623490,0 days 00:00:45.578880,1.224647e-16,1.224647e-16,-1.0,4.067366e-01,0.207912,9.135455e-01,...,0.011989,0.0,16384,16394,2907623,0.0,NaN,2126-05-21T12:13:11Z | RulesEngine,0.075515,1
10696,0.000000,1.000000e+00,1.000000,0 days 00:00:50.272778,0.000000e+00,1.224647e-16,-1.0,2.832769e-16,0.207912,1.000000e+00,...,0.011989,0.0,16384,16394,2909731,0.0,NaN,2126-05-22T00:13:15Z | RulesEngine,0.077591,1
12308,0.000000,-7.071068e-01,1.000000,0 days 00:00:03.174483,7.071068e-01,1.224647e-16,-1.0,-9.945219e-01,-0.743145,-1.045285e-01,...,0.002701,NaN,1001,1000,2911343,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.077876,1
478,-0.433884,-9.659258e-01,-0.900969,0 days 00:00:33.205651,-2.588190e-01,1.224647e-16,-1.0,1.000000e+00,-0.207912,0.000000e+00,...,0.011989,0.0,16384,16394,2899513,0.0,NaN,2126-05-19T13:43:00Z | RulesEngine,0.078057,1
17802,0.781831,-7.071068e-01,0.623490,0 days 00:00:32.209349,-7.071068e-01,1.224647e-16,-1.0,-1.045285e-01,-0.207912,-9.945219e-01,...,0.011989,0.0,16384,16394,2916837,0.0,NaN,2126-05-23T15:17:44Z | RulesEngine,0.078170,1
12333,0.000000,-7.071068e-01,1.000000,0 days 00:00:02.421861,7.071068e-01,1.224647e-16,-1.0,8.090170e-01,-0.809017,5.877853e-01,...,0.001896,NaN,1000,4,2911368,NaN,NaN,httpd.exe | 2.4.41.0 | 5d4d8438 | php7ts.dll |...,0.078259,1
12514,0.000000,-7.071068e-01,1.000000,0 days 00:00:03.860215,7.071068e-01,1.224647e-16,-1.0,5.877853e-01,0.743145,-8.090170e-01,...,0.002701,NaN,1001,1000,2911549,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.078607,1
12479,0.000000,-7.071068e-01,1.000000,0 days 00:00:01.249989,7.071068e-01,1.224647e-16,-1.0,8.660254e-01,0.669131,5.000000e-01,...,0.002701,NaN,1001,4,2911514,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.078791,1
20502,0.974928,6.123234e-17,-0.222521,0 days 00:00:17.032413,1.000000e+00,1.224647e-16,-1.0,-1.000000e+00,-0.951057,5.665539e-16,...,0.002132,0.0,64,16394,2919537,0.0,86 3b a2 db 28 07 24 23 98 c4 c9 49 00 04 e3 a...,Système local,0.079923,1
12393,0.000000,-7.071068e-01,1.000000,0 days 00:00:03.517479,7.071068e-01,1.224647e-16,-1.0,5.877853e-01,-0.978148,-8.090170e-01,...,0.002701,NaN,1001,1000,2911428,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.081296,1
14124,0.000000,-1.836970e-16,1.000000,0 days 00:00:59.491738,-1.000000e+00,1.224647e-16,-1.0,-8.090170e-01,-0.207912,5.877853e-01,...,0.011989,0.0,16384,16394,2913159,0.0,NaN,2126-05-22T18:43:24Z | RulesEngine,0.082026,1
12508,0.000000,-7.071068e-01,1.000000,0 days 00:00:02.655473,7.071068e-01,1.224647e-16,-1.0,-5.000000e-01,0.743145,-8.660254e-01,...,0.001896,NaN,1000,4,2911543,NaN,NaN,httpd.exe | 2.4.41.0 | 5d4d8438 | php7ts.dll |...,0.082427,1
12376,0.000000,-7.071068e-01,1.000000,0 days 00:00:01.062488,7.071068e-01,1.224647e-16,-1.0,-3.090170e-01,-0.978148,9.510565e-01,...,0.001896,NaN,1000,4,2911411,NaN,NaN,httpd.exe | 2.4.41.0 | 5d4d8438 | php7ts.dll |...,0.083348,1
12518,0.000000,-7.071068e-01,1.000000,0 days 00:00:03.453103,7.071068e-01,1.224647e-16,-1.0,9.781476e-01,0.743145,-2.079117e-01,...,0.002701,NaN,1001,1000,2911553,NaN,NaN,2247232631145130785 | 5 | BEX | Non disponible...,0.083401,1
12490,0.000000,-7.071068e-01,1.000000,0 days 00:00:23.173898,7.071068e-01,1.224647e-16,-1.0,3.090170e-01,0.669131,-9.510565e-01,...,0.001896,NaN,1000,4,2911525,NaN,NaN,httpd.exe | 2.4.41.0 | 5d4d8438 | php7ts.dll |...,0.083903,1
12582,0.000000,-8.660254e-01,1.000000,0 days 00:00:55.871544,5.000000e-01,1.224647e-16,-1.0,-9.510565e-01,0.207912,3.090170e-01,...,0.011989,0.0,16384,16394,2911617,0.0,NaN,2126-05-22T10:13:27Z | RulesEngine,0.083909,1
7900,-0.781831,-5.000000e-01,0.623490,0 days 00:00:42.626024,8.660254e-01,1.224647e-16,-1.0,6.691306e-01,0.207912,7.431448e-01,...,0.011989,0.0,16384,16394,2906935,0.0,NaN,2126-05-21T08:13:08Z | RulesEngine,0.084104,1
8759,-0.781831,-9.659258e-01,0.623490,0 days 00:00:32.390809,-2.588190e-01,1.224647e-16,-1.0,9.510565e-01,0.406737,3.090170e-01,...,0.011989,0.0,16384,16394,2907794,0.0,NaN,2126-05-21T13:11:03Z | RulesEngine,0.084424,1
12372,0.000000,-7.071068e-01,1.000000,0 days 00:00:00.125000,7.071068e-01,1.224647e-16,-1.0,9.510565e-01,-0.978148,3.090170e-01,...,0.001896,NaN,1000,4,2911407,NaN,NaN,httpd.exe | 2.4.41.0 | 5d4d8438 | php7ts.dll |...,0.084530,1